// Code generated by ent, DO NOT EDIT.

package metadatacache

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the metadatacache type in the database.
	Label = "metadata_cache"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldNotFound holds the string denoting the not_found field in the database.
	FieldNotFound = "not_found"
	// FieldFetchedAt holds the string denoting the fetched_at field in the database.
	FieldFetchedAt = "fetched_at"
	// Table holds the table name of the metadatacache in the database.
	Table = "metadata_caches"
)

// Columns holds all SQL columns for metadatacache fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldKind,
	FieldKey,
	FieldPayload,
	FieldNotFound,
	FieldFetchedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNotFound holds the default value on creation for the "not_found" field.
	DefaultNotFound bool
	// DefaultFetchedAt holds the default value on creation for the "fetched_at" field.
	DefaultFetchedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MetadataCache queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByNotFound orders the results by the not_found field.
func ByNotFound(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotFound, opts...).ToFunc()
}

// ByFetchedAt orders the results by the fetched_at field.
func ByFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFetchedAt, opts...).ToFunc()
}
