// Code generated by ent, DO NOT EDIT.

package metadatacache

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldProvider, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldKind, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldKey, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v []byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldPayload, v))
}

// NotFound applies equality check predicate on the "not_found" field. It's identical to NotFoundEQ.
func NotFound(v bool) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldNotFound, v))
}

// FetchedAt applies equality check predicate on the "fetched_at" field. It's identical to FetchedAtEQ.
func FetchedAt(v time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldFetchedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldContainsFold(FieldProvider, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldContainsFold(FieldKind, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldContainsFold(FieldKey, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v []byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v []byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...[]byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...[]byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v []byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v []byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v []byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v []byte) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLTE(FieldPayload, v))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNotNull(FieldPayload))
}

// NotFoundEQ applies the EQ predicate on the "not_found" field.
func NotFoundEQ(v bool) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldNotFound, v))
}

// NotFoundNEQ applies the NEQ predicate on the "not_found" field.
func NotFoundNEQ(v bool) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNEQ(FieldNotFound, v))
}

// FetchedAtEQ applies the EQ predicate on the "fetched_at" field.
func FetchedAtEQ(v time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldEQ(FieldFetchedAt, v))
}

// FetchedAtNEQ applies the NEQ predicate on the "fetched_at" field.
func FetchedAtNEQ(v time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNEQ(FieldFetchedAt, v))
}

// FetchedAtIn applies the In predicate on the "fetched_at" field.
func FetchedAtIn(vs ...time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldIn(FieldFetchedAt, vs...))
}

// FetchedAtNotIn applies the NotIn predicate on the "fetched_at" field.
func FetchedAtNotIn(vs ...time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldNotIn(FieldFetchedAt, vs...))
}

// FetchedAtGT applies the GT predicate on the "fetched_at" field.
func FetchedAtGT(v time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGT(FieldFetchedAt, v))
}

// FetchedAtGTE applies the GTE predicate on the "fetched_at" field.
func FetchedAtGTE(v time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldGTE(FieldFetchedAt, v))
}

// FetchedAtLT applies the LT predicate on the "fetched_at" field.
func FetchedAtLT(v time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLT(FieldFetchedAt, v))
}

// FetchedAtLTE applies the LTE predicate on the "fetched_at" field.
func FetchedAtLTE(v time.Time) predicate.MetadataCache {
	return predicate.MetadataCache(sql.FieldLTE(FieldFetchedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MetadataCache) predicate.MetadataCache {
	return predicate.MetadataCache(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MetadataCache) predicate.MetadataCache {
	return predicate.MetadataCache(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MetadataCache) predicate.MetadataCache {
	return predicate.MetadataCache(sql.NotPredicates(p))
}
