// Code generated by ent, DO NOT EDIT.

package mediaitem

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the mediaitem type in the database.
	Label = "media_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSortName holds the string denoting the sort_name field in the database.
	FieldSortName = "sort_name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldMtime holds the string denoting the mtime field in the database.
	FieldMtime = "mtime"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldContainer holds the string denoting the container field in the database.
	FieldContainer = "container"
	// FieldRunTimeTicks holds the string denoting the run_time_ticks field in the database.
	FieldRunTimeTicks = "run_time_ticks"
	// FieldProductionYear holds the string denoting the production_year field in the database.
	FieldProductionYear = "production_year"
	// FieldIndexNumber holds the string denoting the index_number field in the database.
	FieldIndexNumber = "index_number"
	// FieldIndexNumberEnd holds the string denoting the index_number_end field in the database.
	FieldIndexNumberEnd = "index_number_end"
	// FieldParentIndexNumber holds the string denoting the parent_index_number field in the database.
	FieldParentIndexNumber = "parent_index_number"
	// FieldOverview holds the string denoting the overview field in the database.
	FieldOverview = "overview"
	// FieldTagline holds the string denoting the tagline field in the database.
	FieldTagline = "tagline"
	// FieldOfficialRating holds the string denoting the official_rating field in the database.
	FieldOfficialRating = "official_rating"
	// FieldCommunityRating holds the string denoting the community_rating field in the database.
	FieldCommunityRating = "community_rating"
	// FieldPremiereDate holds the string denoting the premiere_date field in the database.
	FieldPremiereDate = "premiere_date"
	// FieldGenres holds the string denoting the genres field in the database.
	FieldGenres = "genres"
	// FieldStudios holds the string denoting the studios field in the database.
	FieldStudios = "studios"
	// FieldPeople holds the string denoting the people field in the database.
	FieldPeople = "people"
	// FieldAlbumArtist holds the string denoting the album_artist field in the database.
	FieldAlbumArtist = "album_artist"
	// FieldImagePath holds the string denoting the image_path field in the database.
	FieldImagePath = "image_path"
	// FieldMediaStreams holds the string denoting the media_streams field in the database.
	FieldMediaStreams = "media_streams"
	// EdgeLibrary holds the string denoting the library edge name in mutations.
	EdgeLibrary = "library"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgePlaystates holds the string denoting the playstates edge name in mutations.
	EdgePlaystates = "playstates"
	// Table holds the table name of the mediaitem in the database.
	Table = "media_items"
	// LibraryTable is the table that holds the library relation/edge.
	LibraryTable = "media_items"
	// LibraryInverseTable is the table name for the Library entity.
	// It exists in this package in order to avoid circular dependency with the "library" package.
	LibraryInverseTable = "libraries"
	// LibraryColumn is the table column denoting the library relation/edge.
	LibraryColumn = "library_items"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "media_items"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "media_item_children"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "media_items"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "media_item_children"
	// PlaystatesTable is the table that holds the playstates relation/edge.
	PlaystatesTable = "play_states"
	// PlaystatesInverseTable is the table name for the PlayState entity.
	// It exists in this package in order to avoid circular dependency with the "playstate" package.
	PlaystatesInverseTable = "play_states"
	// PlaystatesColumn is the table column denoting the playstates relation/edge.
	PlaystatesColumn = "media_item_playstates"
)

// Columns holds all SQL columns for mediaitem fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldName,
	FieldSortName,
	FieldPath,
	FieldMtime,
	FieldSize,
	FieldContainer,
	FieldRunTimeTicks,
	FieldProductionYear,
	FieldIndexNumber,
	FieldIndexNumberEnd,
	FieldParentIndexNumber,
	FieldOverview,
	FieldTagline,
	FieldOfficialRating,
	FieldCommunityRating,
	FieldPremiereDate,
	FieldGenres,
	FieldStudios,
	FieldPeople,
	FieldAlbumArtist,
	FieldImagePath,
	FieldMediaStreams,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "media_items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"library_items",
	"media_item_children",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultSortName holds the default value on creation for the "sort_name" field.
	DefaultSortName string
	// DefaultPath holds the default value on creation for the "path" field.
	DefaultPath string
	// DefaultMtime holds the default value on creation for the "mtime" field.
	DefaultMtime int64
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize int64
	// DefaultContainer holds the default value on creation for the "container" field.
	DefaultContainer string
	// DefaultRunTimeTicks holds the default value on creation for the "run_time_ticks" field.
	DefaultRunTimeTicks int64
	// DefaultOverview holds the default value on creation for the "overview" field.
	DefaultOverview string
	// DefaultTagline holds the default value on creation for the "tagline" field.
	DefaultTagline string
	// DefaultOfficialRating holds the default value on creation for the "official_rating" field.
	DefaultOfficialRating string
	// DefaultAlbumArtist holds the default value on creation for the "album_artist" field.
	DefaultAlbumArtist string
	// DefaultImagePath holds the default value on creation for the "image_path" field.
	DefaultImagePath string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindMovie       Kind = "Movie"
	KindSeries      Kind = "Series"
	KindSeason      Kind = "Season"
	KindEpisode     Kind = "Episode"
	KindMusicArtist Kind = "MusicArtist"
	KindMusicAlbum  Kind = "MusicAlbum"
	KindAudio       Kind = "Audio"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindMovie, KindSeries, KindSeason, KindEpisode, KindMusicArtist, KindMusicAlbum, KindAudio:
		return nil
	default:
		return fmt.Errorf("mediaitem: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the MediaItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySortName orders the results by the sort_name field.
func BySortName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortName, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByMtime orders the results by the mtime field.
func ByMtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMtime, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByContainer orders the results by the container field.
func ByContainer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContainer, opts...).ToFunc()
}

// ByRunTimeTicks orders the results by the run_time_ticks field.
func ByRunTimeTicks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunTimeTicks, opts...).ToFunc()
}

// ByProductionYear orders the results by the production_year field.
func ByProductionYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductionYear, opts...).ToFunc()
}

// ByIndexNumber orders the results by the index_number field.
func ByIndexNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndexNumber, opts...).ToFunc()
}

// ByIndexNumberEnd orders the results by the index_number_end field.
func ByIndexNumberEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndexNumberEnd, opts...).ToFunc()
}

// ByParentIndexNumber orders the results by the parent_index_number field.
func ByParentIndexNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentIndexNumber, opts...).ToFunc()
}

// ByOverview orders the results by the overview field.
func ByOverview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverview, opts...).ToFunc()
}

// ByTagline orders the results by the tagline field.
func ByTagline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTagline, opts...).ToFunc()
}

// ByOfficialRating orders the results by the official_rating field.
func ByOfficialRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfficialRating, opts...).ToFunc()
}

// ByCommunityRating orders the results by the community_rating field.
func ByCommunityRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommunityRating, opts...).ToFunc()
}

// ByPremiereDate orders the results by the premiere_date field.
func ByPremiereDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPremiereDate, opts...).ToFunc()
}

// ByAlbumArtist orders the results by the album_artist field.
func ByAlbumArtist(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlbumArtist, opts...).ToFunc()
}

// ByImagePath orders the results by the image_path field.
func ByImagePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImagePath, opts...).ToFunc()
}

// ByLibraryField orders the results by library field.
func ByLibraryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLibraryStep(), sql.OrderByField(field, opts...))
	}
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPlaystatesCount orders the results by playstates count.
func ByPlaystatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlaystatesStep(), opts...)
	}
}

// ByPlaystates orders the results by playstates terms.
func ByPlaystates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlaystatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLibraryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LibraryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LibraryTable, LibraryColumn),
	)
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
func newPlaystatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlaystatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlaystatesTable, PlaystatesColumn),
	)
}
