// Code generated by ent, DO NOT EDIT.

package mediaitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldName, v))
}

// SortName applies equality check predicate on the "sort_name" field. It's identical to SortNameEQ.
func SortName(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldSortName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldPath, v))
}

// Container applies equality check predicate on the "container" field. It's identical to ContainerEQ.
func Container(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldContainer, v))
}

// RunTimeTicks applies equality check predicate on the "run_time_ticks" field. It's identical to RunTimeTicksEQ.
func RunTimeTicks(v int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldRunTimeTicks, v))
}

// ProductionYear applies equality check predicate on the "production_year" field. It's identical to ProductionYearEQ.
func ProductionYear(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldProductionYear, v))
}

// IndexNumber applies equality check predicate on the "index_number" field. It's identical to IndexNumberEQ.
func IndexNumber(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldIndexNumber, v))
}

// ParentIndexNumber applies equality check predicate on the "parent_index_number" field. It's identical to ParentIndexNumberEQ.
func ParentIndexNumber(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldParentIndexNumber, v))
}

// Overview applies equality check predicate on the "overview" field. It's identical to OverviewEQ.
func Overview(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldOverview, v))
}

// AlbumArtist applies equality check predicate on the "album_artist" field. It's identical to AlbumArtistEQ.
func AlbumArtist(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldAlbumArtist, v))
}

// ImagePath applies equality check predicate on the "image_path" field. It's identical to ImagePathEQ.
func ImagePath(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldImagePath, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldKind, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContainsFold(FieldName, v))
}

// SortNameEQ applies the EQ predicate on the "sort_name" field.
func SortNameEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldSortName, v))
}

// SortNameNEQ applies the NEQ predicate on the "sort_name" field.
func SortNameNEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldSortName, v))
}

// SortNameIn applies the In predicate on the "sort_name" field.
func SortNameIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldSortName, vs...))
}

// SortNameNotIn applies the NotIn predicate on the "sort_name" field.
func SortNameNotIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldSortName, vs...))
}

// SortNameGT applies the GT predicate on the "sort_name" field.
func SortNameGT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldSortName, v))
}

// SortNameGTE applies the GTE predicate on the "sort_name" field.
func SortNameGTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldSortName, v))
}

// SortNameLT applies the LT predicate on the "sort_name" field.
func SortNameLT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldSortName, v))
}

// SortNameLTE applies the LTE predicate on the "sort_name" field.
func SortNameLTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldSortName, v))
}

// SortNameContains applies the Contains predicate on the "sort_name" field.
func SortNameContains(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContains(FieldSortName, v))
}

// SortNameHasPrefix applies the HasPrefix predicate on the "sort_name" field.
func SortNameHasPrefix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasPrefix(FieldSortName, v))
}

// SortNameHasSuffix applies the HasSuffix predicate on the "sort_name" field.
func SortNameHasSuffix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasSuffix(FieldSortName, v))
}

// SortNameEqualFold applies the EqualFold predicate on the "sort_name" field.
func SortNameEqualFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEqualFold(FieldSortName, v))
}

// SortNameContainsFold applies the ContainsFold predicate on the "sort_name" field.
func SortNameContainsFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContainsFold(FieldSortName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContainsFold(FieldPath, v))
}

// ContainerEQ applies the EQ predicate on the "container" field.
func ContainerEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldContainer, v))
}

// ContainerNEQ applies the NEQ predicate on the "container" field.
func ContainerNEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldContainer, v))
}

// ContainerIn applies the In predicate on the "container" field.
func ContainerIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldContainer, vs...))
}

// ContainerNotIn applies the NotIn predicate on the "container" field.
func ContainerNotIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldContainer, vs...))
}

// ContainerGT applies the GT predicate on the "container" field.
func ContainerGT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldContainer, v))
}

// ContainerGTE applies the GTE predicate on the "container" field.
func ContainerGTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldContainer, v))
}

// ContainerLT applies the LT predicate on the "container" field.
func ContainerLT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldContainer, v))
}

// ContainerLTE applies the LTE predicate on the "container" field.
func ContainerLTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldContainer, v))
}

// ContainerContains applies the Contains predicate on the "container" field.
func ContainerContains(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContains(FieldContainer, v))
}

// ContainerHasPrefix applies the HasPrefix predicate on the "container" field.
func ContainerHasPrefix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasPrefix(FieldContainer, v))
}

// ContainerHasSuffix applies the HasSuffix predicate on the "container" field.
func ContainerHasSuffix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasSuffix(FieldContainer, v))
}

// ContainerEqualFold applies the EqualFold predicate on the "container" field.
func ContainerEqualFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEqualFold(FieldContainer, v))
}

// ContainerContainsFold applies the ContainsFold predicate on the "container" field.
func ContainerContainsFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContainsFold(FieldContainer, v))
}

// RunTimeTicksEQ applies the EQ predicate on the "run_time_ticks" field.
func RunTimeTicksEQ(v int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldRunTimeTicks, v))
}

// RunTimeTicksNEQ applies the NEQ predicate on the "run_time_ticks" field.
func RunTimeTicksNEQ(v int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldRunTimeTicks, v))
}

// RunTimeTicksIn applies the In predicate on the "run_time_ticks" field.
func RunTimeTicksIn(vs ...int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldRunTimeTicks, vs...))
}

// RunTimeTicksNotIn applies the NotIn predicate on the "run_time_ticks" field.
func RunTimeTicksNotIn(vs ...int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldRunTimeTicks, vs...))
}

// RunTimeTicksGT applies the GT predicate on the "run_time_ticks" field.
func RunTimeTicksGT(v int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldRunTimeTicks, v))
}

// RunTimeTicksGTE applies the GTE predicate on the "run_time_ticks" field.
func RunTimeTicksGTE(v int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldRunTimeTicks, v))
}

// RunTimeTicksLT applies the LT predicate on the "run_time_ticks" field.
func RunTimeTicksLT(v int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldRunTimeTicks, v))
}

// RunTimeTicksLTE applies the LTE predicate on the "run_time_ticks" field.
func RunTimeTicksLTE(v int64) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldRunTimeTicks, v))
}

// ProductionYearEQ applies the EQ predicate on the "production_year" field.
func ProductionYearEQ(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldProductionYear, v))
}

// ProductionYearNEQ applies the NEQ predicate on the "production_year" field.
func ProductionYearNEQ(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldProductionYear, v))
}

// ProductionYearIn applies the In predicate on the "production_year" field.
func ProductionYearIn(vs ...int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldProductionYear, vs...))
}

// ProductionYearNotIn applies the NotIn predicate on the "production_year" field.
func ProductionYearNotIn(vs ...int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldProductionYear, vs...))
}

// ProductionYearGT applies the GT predicate on the "production_year" field.
func ProductionYearGT(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldProductionYear, v))
}

// ProductionYearGTE applies the GTE predicate on the "production_year" field.
func ProductionYearGTE(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldProductionYear, v))
}

// ProductionYearLT applies the LT predicate on the "production_year" field.
func ProductionYearLT(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldProductionYear, v))
}

// ProductionYearLTE applies the LTE predicate on the "production_year" field.
func ProductionYearLTE(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldProductionYear, v))
}

// ProductionYearIsNil applies the IsNil predicate on the "production_year" field.
func ProductionYearIsNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIsNull(FieldProductionYear))
}

// ProductionYearNotNil applies the NotNil predicate on the "production_year" field.
func ProductionYearNotNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotNull(FieldProductionYear))
}

// IndexNumberEQ applies the EQ predicate on the "index_number" field.
func IndexNumberEQ(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldIndexNumber, v))
}

// IndexNumberNEQ applies the NEQ predicate on the "index_number" field.
func IndexNumberNEQ(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldIndexNumber, v))
}

// IndexNumberIn applies the In predicate on the "index_number" field.
func IndexNumberIn(vs ...int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldIndexNumber, vs...))
}

// IndexNumberNotIn applies the NotIn predicate on the "index_number" field.
func IndexNumberNotIn(vs ...int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldIndexNumber, vs...))
}

// IndexNumberGT applies the GT predicate on the "index_number" field.
func IndexNumberGT(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldIndexNumber, v))
}

// IndexNumberGTE applies the GTE predicate on the "index_number" field.
func IndexNumberGTE(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldIndexNumber, v))
}

// IndexNumberLT applies the LT predicate on the "index_number" field.
func IndexNumberLT(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldIndexNumber, v))
}

// IndexNumberLTE applies the LTE predicate on the "index_number" field.
func IndexNumberLTE(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldIndexNumber, v))
}

// IndexNumberIsNil applies the IsNil predicate on the "index_number" field.
func IndexNumberIsNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIsNull(FieldIndexNumber))
}

// IndexNumberNotNil applies the NotNil predicate on the "index_number" field.
func IndexNumberNotNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotNull(FieldIndexNumber))
}

// ParentIndexNumberEQ applies the EQ predicate on the "parent_index_number" field.
func ParentIndexNumberEQ(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldParentIndexNumber, v))
}

// ParentIndexNumberNEQ applies the NEQ predicate on the "parent_index_number" field.
func ParentIndexNumberNEQ(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldParentIndexNumber, v))
}

// ParentIndexNumberIn applies the In predicate on the "parent_index_number" field.
func ParentIndexNumberIn(vs ...int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldParentIndexNumber, vs...))
}

// ParentIndexNumberNotIn applies the NotIn predicate on the "parent_index_number" field.
func ParentIndexNumberNotIn(vs ...int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldParentIndexNumber, vs...))
}

// ParentIndexNumberGT applies the GT predicate on the "parent_index_number" field.
func ParentIndexNumberGT(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldParentIndexNumber, v))
}

// ParentIndexNumberGTE applies the GTE predicate on the "parent_index_number" field.
func ParentIndexNumberGTE(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldParentIndexNumber, v))
}

// ParentIndexNumberLT applies the LT predicate on the "parent_index_number" field.
func ParentIndexNumberLT(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldParentIndexNumber, v))
}

// ParentIndexNumberLTE applies the LTE predicate on the "parent_index_number" field.
func ParentIndexNumberLTE(v int32) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldParentIndexNumber, v))
}

// ParentIndexNumberIsNil applies the IsNil predicate on the "parent_index_number" field.
func ParentIndexNumberIsNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIsNull(FieldParentIndexNumber))
}

// ParentIndexNumberNotNil applies the NotNil predicate on the "parent_index_number" field.
func ParentIndexNumberNotNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotNull(FieldParentIndexNumber))
}

// OverviewEQ applies the EQ predicate on the "overview" field.
func OverviewEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldOverview, v))
}

// OverviewNEQ applies the NEQ predicate on the "overview" field.
func OverviewNEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldOverview, v))
}

// OverviewIn applies the In predicate on the "overview" field.
func OverviewIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldOverview, vs...))
}

// OverviewNotIn applies the NotIn predicate on the "overview" field.
func OverviewNotIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldOverview, vs...))
}

// OverviewGT applies the GT predicate on the "overview" field.
func OverviewGT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldOverview, v))
}

// OverviewGTE applies the GTE predicate on the "overview" field.
func OverviewGTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldOverview, v))
}

// OverviewLT applies the LT predicate on the "overview" field.
func OverviewLT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldOverview, v))
}

// OverviewLTE applies the LTE predicate on the "overview" field.
func OverviewLTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldOverview, v))
}

// OverviewContains applies the Contains predicate on the "overview" field.
func OverviewContains(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContains(FieldOverview, v))
}

// OverviewHasPrefix applies the HasPrefix predicate on the "overview" field.
func OverviewHasPrefix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasPrefix(FieldOverview, v))
}

// OverviewHasSuffix applies the HasSuffix predicate on the "overview" field.
func OverviewHasSuffix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasSuffix(FieldOverview, v))
}

// OverviewEqualFold applies the EqualFold predicate on the "overview" field.
func OverviewEqualFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEqualFold(FieldOverview, v))
}

// OverviewContainsFold applies the ContainsFold predicate on the "overview" field.
func OverviewContainsFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContainsFold(FieldOverview, v))
}

// AlbumArtistEQ applies the EQ predicate on the "album_artist" field.
func AlbumArtistEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldAlbumArtist, v))
}

// AlbumArtistNEQ applies the NEQ predicate on the "album_artist" field.
func AlbumArtistNEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldAlbumArtist, v))
}

// AlbumArtistIn applies the In predicate on the "album_artist" field.
func AlbumArtistIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldAlbumArtist, vs...))
}

// AlbumArtistNotIn applies the NotIn predicate on the "album_artist" field.
func AlbumArtistNotIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldAlbumArtist, vs...))
}

// AlbumArtistGT applies the GT predicate on the "album_artist" field.
func AlbumArtistGT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldAlbumArtist, v))
}

// AlbumArtistGTE applies the GTE predicate on the "album_artist" field.
func AlbumArtistGTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldAlbumArtist, v))
}

// AlbumArtistLT applies the LT predicate on the "album_artist" field.
func AlbumArtistLT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldAlbumArtist, v))
}

// AlbumArtistLTE applies the LTE predicate on the "album_artist" field.
func AlbumArtistLTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldAlbumArtist, v))
}

// AlbumArtistContains applies the Contains predicate on the "album_artist" field.
func AlbumArtistContains(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContains(FieldAlbumArtist, v))
}

// AlbumArtistHasPrefix applies the HasPrefix predicate on the "album_artist" field.
func AlbumArtistHasPrefix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasPrefix(FieldAlbumArtist, v))
}

// AlbumArtistHasSuffix applies the HasSuffix predicate on the "album_artist" field.
func AlbumArtistHasSuffix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasSuffix(FieldAlbumArtist, v))
}

// AlbumArtistEqualFold applies the EqualFold predicate on the "album_artist" field.
func AlbumArtistEqualFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEqualFold(FieldAlbumArtist, v))
}

// AlbumArtistContainsFold applies the ContainsFold predicate on the "album_artist" field.
func AlbumArtistContainsFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContainsFold(FieldAlbumArtist, v))
}

// ImagePathEQ applies the EQ predicate on the "image_path" field.
func ImagePathEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEQ(FieldImagePath, v))
}

// ImagePathNEQ applies the NEQ predicate on the "image_path" field.
func ImagePathNEQ(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNEQ(FieldImagePath, v))
}

// ImagePathIn applies the In predicate on the "image_path" field.
func ImagePathIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIn(FieldImagePath, vs...))
}

// ImagePathNotIn applies the NotIn predicate on the "image_path" field.
func ImagePathNotIn(vs ...string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotIn(FieldImagePath, vs...))
}

// ImagePathGT applies the GT predicate on the "image_path" field.
func ImagePathGT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGT(FieldImagePath, v))
}

// ImagePathGTE applies the GTE predicate on the "image_path" field.
func ImagePathGTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldGTE(FieldImagePath, v))
}

// ImagePathLT applies the LT predicate on the "image_path" field.
func ImagePathLT(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLT(FieldImagePath, v))
}

// ImagePathLTE applies the LTE predicate on the "image_path" field.
func ImagePathLTE(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldLTE(FieldImagePath, v))
}

// ImagePathContains applies the Contains predicate on the "image_path" field.
func ImagePathContains(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContains(FieldImagePath, v))
}

// ImagePathHasPrefix applies the HasPrefix predicate on the "image_path" field.
func ImagePathHasPrefix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasPrefix(FieldImagePath, v))
}

// ImagePathHasSuffix applies the HasSuffix predicate on the "image_path" field.
func ImagePathHasSuffix(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldHasSuffix(FieldImagePath, v))
}

// ImagePathEqualFold applies the EqualFold predicate on the "image_path" field.
func ImagePathEqualFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldEqualFold(FieldImagePath, v))
}

// ImagePathContainsFold applies the ContainsFold predicate on the "image_path" field.
func ImagePathContainsFold(v string) predicate.MediaItem {
	return predicate.MediaItem(sql.FieldContainsFold(FieldImagePath, v))
}

// MediaStreamsIsNil applies the IsNil predicate on the "media_streams" field.
func MediaStreamsIsNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldIsNull(FieldMediaStreams))
}

// MediaStreamsNotNil applies the NotNil predicate on the "media_streams" field.
func MediaStreamsNotNil() predicate.MediaItem {
	return predicate.MediaItem(sql.FieldNotNull(FieldMediaStreams))
}

// HasLibrary applies the HasEdge predicate on the "library" edge.
func HasLibrary() predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LibraryTable, LibraryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLibraryWith applies the HasEdge predicate on the "library" edge with a given conditions (other predicates).
func HasLibraryWith(preds ...predicate.Library) predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := newLibraryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.MediaItem) predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.MediaItem) predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlaystates applies the HasEdge predicate on the "playstates" edge.
func HasPlaystates() predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaystatesTable, PlaystatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaystatesWith applies the HasEdge predicate on the "playstates" edge with a given conditions (other predicates).
func HasPlaystatesWith(preds ...predicate.PlayState) predicate.MediaItem {
	return predicate.MediaItem(func(s *sql.Selector) {
		step := newPlaystatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaItem) predicate.MediaItem {
	return predicate.MediaItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaItem) predicate.MediaItem {
	return predicate.MediaItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaItem) predicate.MediaItem {
	return predicate.MediaItem(sql.NotPredicates(p))
}
