// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessTokensColumns holds the columns for the "access_tokens" table.
	AccessTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "client", Type: field.TypeString, Default: ""},
		{Name: "device", Type: field.TypeString, Default: ""},
		{Name: "device_id", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_tokens", Type: field.TypeUUID},
	}
	// AccessTokensTable holds the schema information for the "access_tokens" table.
	AccessTokensTable = &schema.Table{
		Name:       "access_tokens",
		Columns:    AccessTokensColumns,
		PrimaryKey: []*schema.Column{AccessTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "access_tokens_users_tokens",
				Columns:    []*schema.Column{AccessTokensColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LibrariesColumns holds the columns for the "libraries" table.
	LibrariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"movies", "tvshows", "music"}},
		{Name: "path", Type: field.TypeString},
	}
	// LibrariesTable holds the schema information for the "libraries" table.
	LibrariesTable = &schema.Table{
		Name:       "libraries",
		Columns:    LibrariesColumns,
		PrimaryKey: []*schema.Column{LibrariesColumns[0]},
	}
	// MediaItemsColumns holds the columns for the "media_items" table.
	MediaItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"Movie", "Series", "Season", "Episode", "MusicArtist", "MusicAlbum", "Audio"}},
		{Name: "name", Type: field.TypeString},
		{Name: "sort_name", Type: field.TypeString, Default: ""},
		{Name: "path", Type: field.TypeString, Default: ""},
		{Name: "mtime", Type: field.TypeInt64, Default: 0},
		{Name: "size", Type: field.TypeInt64, Default: 0},
		{Name: "container", Type: field.TypeString, Default: ""},
		{Name: "run_time_ticks", Type: field.TypeInt64, Default: 0},
		{Name: "production_year", Type: field.TypeInt32, Nullable: true},
		{Name: "index_number", Type: field.TypeInt32, Nullable: true},
		{Name: "index_number_end", Type: field.TypeInt32, Nullable: true},
		{Name: "parent_index_number", Type: field.TypeInt32, Nullable: true},
		{Name: "overview", Type: field.TypeString, Default: ""},
		{Name: "tagline", Type: field.TypeString, Default: ""},
		{Name: "official_rating", Type: field.TypeString, Default: ""},
		{Name: "community_rating", Type: field.TypeFloat32, Nullable: true},
		{Name: "premiere_date", Type: field.TypeTime, Nullable: true},
		{Name: "genres", Type: field.TypeJSON, Nullable: true},
		{Name: "studios", Type: field.TypeJSON, Nullable: true},
		{Name: "people", Type: field.TypeJSON, Nullable: true},
		{Name: "album_artist", Type: field.TypeString, Default: ""},
		{Name: "image_path", Type: field.TypeString, Default: ""},
		{Name: "media_streams", Type: field.TypeJSON, Nullable: true},
		{Name: "lock_data", Type: field.TypeBool, Default: false},
		{Name: "locked_fields", Type: field.TypeJSON, Nullable: true},
		{Name: "library_items", Type: field.TypeUUID, Nullable: true},
		{Name: "media_item_children", Type: field.TypeUUID, Nullable: true},
	}
	// MediaItemsTable holds the schema information for the "media_items" table.
	MediaItemsTable = &schema.Table{
		Name:       "media_items",
		Columns:    MediaItemsColumns,
		PrimaryKey: []*schema.Column{MediaItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_items_libraries_items",
				Columns:    []*schema.Column{MediaItemsColumns[26]},
				RefColumns: []*schema.Column{LibrariesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "media_items_media_items_children",
				Columns:    []*schema.Column{MediaItemsColumns[27]},
				RefColumns: []*schema.Column{MediaItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mediaitem_path",
				Unique:  false,
				Columns: []*schema.Column{MediaItemsColumns[4]},
			},
		},
	}
	// PlayStatesColumns holds the columns for the "play_states" table.
	PlayStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "played", Type: field.TypeBool, Default: false},
		{Name: "playback_position_ticks", Type: field.TypeInt64, Default: 0},
		{Name: "play_count", Type: field.TypeInt, Default: 0},
		{Name: "last_played_date", Type: field.TypeTime, Nullable: true},
		{Name: "media_item_playstates", Type: field.TypeUUID},
		{Name: "user_playstates", Type: field.TypeUUID},
	}
	// PlayStatesTable holds the schema information for the "play_states" table.
	PlayStatesTable = &schema.Table{
		Name:       "play_states",
		Columns:    PlayStatesColumns,
		PrimaryKey: []*schema.Column{PlayStatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "play_states_media_items_playstates",
				Columns:    []*schema.Column{PlayStatesColumns[5]},
				RefColumns: []*schema.Column{MediaItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "play_states_users_playstates",
				Columns:    []*schema.Column{PlayStatesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessTokensTable,
		LibrariesTable,
		MediaItemsTable,
		PlayStatesTable,
		UsersTable,
	}
)

func init() {
	AccessTokensTable.ForeignKeys[0].RefTable = UsersTable
	MediaItemsTable.ForeignKeys[0].RefTable = LibrariesTable
	MediaItemsTable.ForeignKeys[1].RefTable = MediaItemsTable
	PlayStatesTable.ForeignKeys[0].RefTable = MediaItemsTable
	PlayStatesTable.ForeignKeys[1].RefTable = UsersTable
}
