// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/accesstoken"
	"github.com/gartnera/gofin/ent/user"
	"github.com/google/uuid"
)

// AccessTokenCreate is the builder for creating a AccessToken entity.
type AccessTokenCreate struct {
	config
	mutation *AccessTokenMutation
	hooks    []Hook
}

// SetToken sets the "token" field.
func (_c *AccessTokenCreate) SetToken(v string) *AccessTokenCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetClient sets the "client" field.
func (_c *AccessTokenCreate) SetClient(v string) *AccessTokenCreate {
	_c.mutation.SetClient(v)
	return _c
}

// SetNillableClient sets the "client" field if the given value is not nil.
func (_c *AccessTokenCreate) SetNillableClient(v *string) *AccessTokenCreate {
	if v != nil {
		_c.SetClient(*v)
	}
	return _c
}

// SetDevice sets the "device" field.
func (_c *AccessTokenCreate) SetDevice(v string) *AccessTokenCreate {
	_c.mutation.SetDevice(v)
	return _c
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_c *AccessTokenCreate) SetNillableDevice(v *string) *AccessTokenCreate {
	if v != nil {
		_c.SetDevice(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *AccessTokenCreate) SetDeviceID(v string) *AccessTokenCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *AccessTokenCreate) SetNillableDeviceID(v *string) *AccessTokenCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *AccessTokenCreate) SetVersion(v string) *AccessTokenCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *AccessTokenCreate) SetNillableVersion(v *string) *AccessTokenCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessTokenCreate) SetCreatedAt(v time.Time) *AccessTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessTokenCreate) SetNillableCreatedAt(v *time.Time) *AccessTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AccessTokenCreate) SetUserID(id uuid.UUID) *AccessTokenCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccessTokenCreate) SetUser(v *User) *AccessTokenCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccessTokenMutation object of the builder.
func (_c *AccessTokenCreate) Mutation() *AccessTokenMutation {
	return _c.mutation
}

// Save creates the AccessToken in the database.
func (_c *AccessTokenCreate) Save(ctx context.Context) (*AccessToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessTokenCreate) SaveX(ctx context.Context) *AccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessTokenCreate) defaults() {
	if _, ok := _c.mutation.GetClient(); !ok {
		v := accesstoken.DefaultClient
		_c.mutation.SetClient(v)
	}
	if _, ok := _c.mutation.Device(); !ok {
		v := accesstoken.DefaultDevice
		_c.mutation.SetDevice(v)
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		v := accesstoken.DefaultDeviceID
		_c.mutation.SetDeviceID(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := accesstoken.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accesstoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessTokenCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "AccessToken.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := accesstoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "AccessToken.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetClient(); !ok {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required field "AccessToken.client"`)}
	}
	if _, ok := _c.mutation.Device(); !ok {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required field "AccessToken.device"`)}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "AccessToken.device_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "AccessToken.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessToken.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccessToken.user"`)}
	}
	return nil
}

func (_c *AccessTokenCreate) sqlSave(ctx context.Context) (*AccessToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessTokenCreate) createSpec() (*AccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accesstoken.Table, sqlgraph.NewFieldSpec(accesstoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(accesstoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.GetClient(); ok {
		_spec.SetField(accesstoken.FieldClient, field.TypeString, value)
		_node.Client = value
	}
	if value, ok := _c.mutation.Device(); ok {
		_spec.SetField(accesstoken.FieldDevice, field.TypeString, value)
		_node.Device = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(accesstoken.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(accesstoken.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accesstoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesstoken.UserTable,
			Columns: []string{accesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccessTokenCreateBulk is the builder for creating many AccessToken entities in bulk.
type AccessTokenCreateBulk struct {
	config
	err      error
	builders []*AccessTokenCreate
}

// Save creates the AccessToken entities in the database.
func (_c *AccessTokenCreateBulk) Save(ctx context.Context) ([]*AccessToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessTokenCreateBulk) SaveX(ctx context.Context) []*AccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
