// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/accesstoken"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/gartnera/gofin/ent/user"
	"github.com/google/uuid"
)

// AccessTokenUpdate is the builder for updating AccessToken entities.
type AccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *AccessTokenMutation
}

// Where appends a list predicates to the AccessTokenUpdate builder.
func (_u *AccessTokenUpdate) Where(ps ...predicate.AccessToken) *AccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *AccessTokenUpdate) SetToken(v string) *AccessTokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *AccessTokenUpdate) SetNillableToken(v *string) *AccessTokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetClient sets the "client" field.
func (_u *AccessTokenUpdate) SetClient(v string) *AccessTokenUpdate {
	_u.mutation.SetClient(v)
	return _u
}

// SetNillableClient sets the "client" field if the given value is not nil.
func (_u *AccessTokenUpdate) SetNillableClient(v *string) *AccessTokenUpdate {
	if v != nil {
		_u.SetClient(*v)
	}
	return _u
}

// SetDevice sets the "device" field.
func (_u *AccessTokenUpdate) SetDevice(v string) *AccessTokenUpdate {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *AccessTokenUpdate) SetNillableDevice(v *string) *AccessTokenUpdate {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *AccessTokenUpdate) SetDeviceID(v string) *AccessTokenUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *AccessTokenUpdate) SetNillableDeviceID(v *string) *AccessTokenUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccessTokenUpdate) SetVersion(v string) *AccessTokenUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccessTokenUpdate) SetNillableVersion(v *string) *AccessTokenUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AccessTokenUpdate) SetUserID(id uuid.UUID) *AccessTokenUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccessTokenUpdate) SetUser(v *User) *AccessTokenUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccessTokenMutation object of the builder.
func (_u *AccessTokenUpdate) Mutation() *AccessTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccessTokenUpdate) ClearUser() *AccessTokenUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessTokenUpdate) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := accesstoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "AccessToken.token": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccessToken.user"`)
	}
	return nil
}

func (_u *AccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesstoken.Table, accesstoken.Columns, sqlgraph.NewFieldSpec(accesstoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(accesstoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetClient(); ok {
		_spec.SetField(accesstoken.FieldClient, field.TypeString, value)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(accesstoken.FieldDevice, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(accesstoken.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accesstoken.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesstoken.UserTable,
			Columns: []string{accesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesstoken.UserTable,
			Columns: []string{accesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessTokenUpdateOne is the builder for updating a single AccessToken entity.
type AccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessTokenMutation
}

// SetToken sets the "token" field.
func (_u *AccessTokenUpdateOne) SetToken(v string) *AccessTokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *AccessTokenUpdateOne) SetNillableToken(v *string) *AccessTokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetClient sets the "client" field.
func (_u *AccessTokenUpdateOne) SetClient(v string) *AccessTokenUpdateOne {
	_u.mutation.SetClient(v)
	return _u
}

// SetNillableClient sets the "client" field if the given value is not nil.
func (_u *AccessTokenUpdateOne) SetNillableClient(v *string) *AccessTokenUpdateOne {
	if v != nil {
		_u.SetClient(*v)
	}
	return _u
}

// SetDevice sets the "device" field.
func (_u *AccessTokenUpdateOne) SetDevice(v string) *AccessTokenUpdateOne {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *AccessTokenUpdateOne) SetNillableDevice(v *string) *AccessTokenUpdateOne {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *AccessTokenUpdateOne) SetDeviceID(v string) *AccessTokenUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *AccessTokenUpdateOne) SetNillableDeviceID(v *string) *AccessTokenUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccessTokenUpdateOne) SetVersion(v string) *AccessTokenUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccessTokenUpdateOne) SetNillableVersion(v *string) *AccessTokenUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AccessTokenUpdateOne) SetUserID(id uuid.UUID) *AccessTokenUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccessTokenUpdateOne) SetUser(v *User) *AccessTokenUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccessTokenMutation object of the builder.
func (_u *AccessTokenUpdateOne) Mutation() *AccessTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccessTokenUpdateOne) ClearUser() *AccessTokenUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AccessTokenUpdate builder.
func (_u *AccessTokenUpdateOne) Where(ps ...predicate.AccessToken) *AccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessTokenUpdateOne) Select(field string, fields ...string) *AccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessToken entity.
func (_u *AccessTokenUpdateOne) Save(ctx context.Context) (*AccessToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessTokenUpdateOne) SaveX(ctx context.Context) *AccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := accesstoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "AccessToken.token": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccessToken.user"`)
	}
	return nil
}

func (_u *AccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *AccessToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesstoken.Table, accesstoken.Columns, sqlgraph.NewFieldSpec(accesstoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesstoken.FieldID)
		for _, f := range fields {
			if !accesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(accesstoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetClient(); ok {
		_spec.SetField(accesstoken.FieldClient, field.TypeString, value)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(accesstoken.FieldDevice, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(accesstoken.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accesstoken.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesstoken.UserTable,
			Columns: []string{accesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesstoken.UserTable,
			Columns: []string{accesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
