// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/library"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/google/uuid"
)

// MediaItemCreate is the builder for creating a MediaItem entity.
type MediaItemCreate struct {
	config
	mutation *MediaItemMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (_c *MediaItemCreate) SetKind(v mediaitem.Kind) *MediaItemCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetName sets the "name" field.
func (_c *MediaItemCreate) SetName(v string) *MediaItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSortName sets the "sort_name" field.
func (_c *MediaItemCreate) SetSortName(v string) *MediaItemCreate {
	_c.mutation.SetSortName(v)
	return _c
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableSortName(v *string) *MediaItemCreate {
	if v != nil {
		_c.SetSortName(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *MediaItemCreate) SetPath(v string) *MediaItemCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillablePath(v *string) *MediaItemCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetContainer sets the "container" field.
func (_c *MediaItemCreate) SetContainer(v string) *MediaItemCreate {
	_c.mutation.SetContainer(v)
	return _c
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableContainer(v *string) *MediaItemCreate {
	if v != nil {
		_c.SetContainer(*v)
	}
	return _c
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (_c *MediaItemCreate) SetRunTimeTicks(v int64) *MediaItemCreate {
	_c.mutation.SetRunTimeTicks(v)
	return _c
}

// SetNillableRunTimeTicks sets the "run_time_ticks" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableRunTimeTicks(v *int64) *MediaItemCreate {
	if v != nil {
		_c.SetRunTimeTicks(*v)
	}
	return _c
}

// SetProductionYear sets the "production_year" field.
func (_c *MediaItemCreate) SetProductionYear(v int32) *MediaItemCreate {
	_c.mutation.SetProductionYear(v)
	return _c
}

// SetNillableProductionYear sets the "production_year" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableProductionYear(v *int32) *MediaItemCreate {
	if v != nil {
		_c.SetProductionYear(*v)
	}
	return _c
}

// SetIndexNumber sets the "index_number" field.
func (_c *MediaItemCreate) SetIndexNumber(v int32) *MediaItemCreate {
	_c.mutation.SetIndexNumber(v)
	return _c
}

// SetNillableIndexNumber sets the "index_number" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableIndexNumber(v *int32) *MediaItemCreate {
	if v != nil {
		_c.SetIndexNumber(*v)
	}
	return _c
}

// SetParentIndexNumber sets the "parent_index_number" field.
func (_c *MediaItemCreate) SetParentIndexNumber(v int32) *MediaItemCreate {
	_c.mutation.SetParentIndexNumber(v)
	return _c
}

// SetNillableParentIndexNumber sets the "parent_index_number" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableParentIndexNumber(v *int32) *MediaItemCreate {
	if v != nil {
		_c.SetParentIndexNumber(*v)
	}
	return _c
}

// SetOverview sets the "overview" field.
func (_c *MediaItemCreate) SetOverview(v string) *MediaItemCreate {
	_c.mutation.SetOverview(v)
	return _c
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableOverview(v *string) *MediaItemCreate {
	if v != nil {
		_c.SetOverview(*v)
	}
	return _c
}

// SetAlbumArtist sets the "album_artist" field.
func (_c *MediaItemCreate) SetAlbumArtist(v string) *MediaItemCreate {
	_c.mutation.SetAlbumArtist(v)
	return _c
}

// SetNillableAlbumArtist sets the "album_artist" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableAlbumArtist(v *string) *MediaItemCreate {
	if v != nil {
		_c.SetAlbumArtist(*v)
	}
	return _c
}

// SetImagePath sets the "image_path" field.
func (_c *MediaItemCreate) SetImagePath(v string) *MediaItemCreate {
	_c.mutation.SetImagePath(v)
	return _c
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableImagePath(v *string) *MediaItemCreate {
	if v != nil {
		_c.SetImagePath(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaItemCreate) SetID(v uuid.UUID) *MediaItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MediaItemCreate) SetNillableID(v *uuid.UUID) *MediaItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLibraryID sets the "library" edge to the Library entity by ID.
func (_c *MediaItemCreate) SetLibraryID(id uuid.UUID) *MediaItemCreate {
	_c.mutation.SetLibraryID(id)
	return _c
}

// SetNillableLibraryID sets the "library" edge to the Library entity by ID if the given value is not nil.
func (_c *MediaItemCreate) SetNillableLibraryID(id *uuid.UUID) *MediaItemCreate {
	if id != nil {
		_c = _c.SetLibraryID(*id)
	}
	return _c
}

// SetLibrary sets the "library" edge to the Library entity.
func (_c *MediaItemCreate) SetLibrary(v *Library) *MediaItemCreate {
	return _c.SetLibraryID(v.ID)
}

// SetParentID sets the "parent" edge to the MediaItem entity by ID.
func (_c *MediaItemCreate) SetParentID(id uuid.UUID) *MediaItemCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the MediaItem entity by ID if the given value is not nil.
func (_c *MediaItemCreate) SetNillableParentID(id *uuid.UUID) *MediaItemCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the MediaItem entity.
func (_c *MediaItemCreate) SetParent(v *MediaItem) *MediaItemCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the MediaItem entity by IDs.
func (_c *MediaItemCreate) AddChildIDs(ids ...uuid.UUID) *MediaItemCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the MediaItem entity.
func (_c *MediaItemCreate) AddChildren(v ...*MediaItem) *MediaItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the MediaItemMutation object of the builder.
func (_c *MediaItemCreate) Mutation() *MediaItemMutation {
	return _c.mutation
}

// Save creates the MediaItem in the database.
func (_c *MediaItemCreate) Save(ctx context.Context) (*MediaItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaItemCreate) SaveX(ctx context.Context) *MediaItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaItemCreate) defaults() {
	if _, ok := _c.mutation.SortName(); !ok {
		v := mediaitem.DefaultSortName
		_c.mutation.SetSortName(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := mediaitem.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.Container(); !ok {
		v := mediaitem.DefaultContainer
		_c.mutation.SetContainer(v)
	}
	if _, ok := _c.mutation.RunTimeTicks(); !ok {
		v := mediaitem.DefaultRunTimeTicks
		_c.mutation.SetRunTimeTicks(v)
	}
	if _, ok := _c.mutation.Overview(); !ok {
		v := mediaitem.DefaultOverview
		_c.mutation.SetOverview(v)
	}
	if _, ok := _c.mutation.AlbumArtist(); !ok {
		v := mediaitem.DefaultAlbumArtist
		_c.mutation.SetAlbumArtist(v)
	}
	if _, ok := _c.mutation.ImagePath(); !ok {
		v := mediaitem.DefaultImagePath
		_c.mutation.SetImagePath(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mediaitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaItemCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "MediaItem.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := mediaitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaItem.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MediaItem.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := mediaitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaItem.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortName(); !ok {
		return &ValidationError{Name: "sort_name", err: errors.New(`ent: missing required field "MediaItem.sort_name"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "MediaItem.path"`)}
	}
	if _, ok := _c.mutation.Container(); !ok {
		return &ValidationError{Name: "container", err: errors.New(`ent: missing required field "MediaItem.container"`)}
	}
	if _, ok := _c.mutation.RunTimeTicks(); !ok {
		return &ValidationError{Name: "run_time_ticks", err: errors.New(`ent: missing required field "MediaItem.run_time_ticks"`)}
	}
	if _, ok := _c.mutation.Overview(); !ok {
		return &ValidationError{Name: "overview", err: errors.New(`ent: missing required field "MediaItem.overview"`)}
	}
	if _, ok := _c.mutation.AlbumArtist(); !ok {
		return &ValidationError{Name: "album_artist", err: errors.New(`ent: missing required field "MediaItem.album_artist"`)}
	}
	if _, ok := _c.mutation.ImagePath(); !ok {
		return &ValidationError{Name: "image_path", err: errors.New(`ent: missing required field "MediaItem.image_path"`)}
	}
	return nil
}

func (_c *MediaItemCreate) sqlSave(ctx context.Context) (*MediaItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaItemCreate) createSpec() (*MediaItem, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaitem.Table, sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(mediaitem.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(mediaitem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SortName(); ok {
		_spec.SetField(mediaitem.FieldSortName, field.TypeString, value)
		_node.SortName = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(mediaitem.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Container(); ok {
		_spec.SetField(mediaitem.FieldContainer, field.TypeString, value)
		_node.Container = value
	}
	if value, ok := _c.mutation.RunTimeTicks(); ok {
		_spec.SetField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
		_node.RunTimeTicks = value
	}
	if value, ok := _c.mutation.ProductionYear(); ok {
		_spec.SetField(mediaitem.FieldProductionYear, field.TypeInt32, value)
		_node.ProductionYear = &value
	}
	if value, ok := _c.mutation.IndexNumber(); ok {
		_spec.SetField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
		_node.IndexNumber = &value
	}
	if value, ok := _c.mutation.ParentIndexNumber(); ok {
		_spec.SetField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
		_node.ParentIndexNumber = &value
	}
	if value, ok := _c.mutation.Overview(); ok {
		_spec.SetField(mediaitem.FieldOverview, field.TypeString, value)
		_node.Overview = value
	}
	if value, ok := _c.mutation.AlbumArtist(); ok {
		_spec.SetField(mediaitem.FieldAlbumArtist, field.TypeString, value)
		_node.AlbumArtist = value
	}
	if value, ok := _c.mutation.ImagePath(); ok {
		_spec.SetField(mediaitem.FieldImagePath, field.TypeString, value)
		_node.ImagePath = value
	}
	if nodes := _c.mutation.LibraryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.library_items = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.media_item_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaItemCreateBulk is the builder for creating many MediaItem entities in bulk.
type MediaItemCreateBulk struct {
	config
	err      error
	builders []*MediaItemCreate
}

// Save creates the MediaItem entities in the database.
func (_c *MediaItemCreateBulk) Save(ctx context.Context) ([]*MediaItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaItemCreateBulk) SaveX(ctx context.Context) []*MediaItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
