// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gartnera/gofin/ent/library"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/internal/probe"
	"github.com/google/uuid"
)

// MediaItem is the model entity for the MediaItem schema.
type MediaItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind mediaitem.Kind `json:"kind,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SortName holds the value of the "sort_name" field.
	SortName string `json:"sort_name,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Container holds the value of the "container" field.
	Container string `json:"container,omitempty"`
	// RunTimeTicks holds the value of the "run_time_ticks" field.
	RunTimeTicks int64 `json:"run_time_ticks,omitempty"`
	// ProductionYear holds the value of the "production_year" field.
	ProductionYear *int32 `json:"production_year,omitempty"`
	// IndexNumber holds the value of the "index_number" field.
	IndexNumber *int32 `json:"index_number,omitempty"`
	// ParentIndexNumber holds the value of the "parent_index_number" field.
	ParentIndexNumber *int32 `json:"parent_index_number,omitempty"`
	// Overview holds the value of the "overview" field.
	Overview string `json:"overview,omitempty"`
	// AlbumArtist holds the value of the "album_artist" field.
	AlbumArtist string `json:"album_artist,omitempty"`
	// ImagePath holds the value of the "image_path" field.
	ImagePath string `json:"image_path,omitempty"`
	// MediaStreams holds the value of the "media_streams" field.
	MediaStreams []probe.Stream `json:"media_streams,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaItemQuery when eager-loading is set.
	Edges               MediaItemEdges `json:"edges"`
	library_items       *uuid.UUID
	media_item_children *uuid.UUID
	selectValues        sql.SelectValues
}

// MediaItemEdges holds the relations/edges for other nodes in the graph.
type MediaItemEdges struct {
	// Library holds the value of the library edge.
	Library *Library `json:"library,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *MediaItem `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*MediaItem `json:"children,omitempty"`
	// Playstates holds the value of the playstates edge.
	Playstates []*PlayState `json:"playstates,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// LibraryOrErr returns the Library value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaItemEdges) LibraryOrErr() (*Library, error) {
	if e.Library != nil {
		return e.Library, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: library.Label}
	}
	return nil, &NotLoadedError{edge: "library"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaItemEdges) ParentOrErr() (*MediaItem, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: mediaitem.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e MediaItemEdges) ChildrenOrErr() ([]*MediaItem, error) {
	if e.loadedTypes[2] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// PlaystatesOrErr returns the Playstates value or an error if the edge
// was not loaded in eager-loading.
func (e MediaItemEdges) PlaystatesOrErr() ([]*PlayState, error) {
	if e.loadedTypes[3] {
		return e.Playstates, nil
	}
	return nil, &NotLoadedError{edge: "playstates"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediaitem.FieldMediaStreams:
			values[i] = new([]byte)
		case mediaitem.FieldRunTimeTicks, mediaitem.FieldProductionYear, mediaitem.FieldIndexNumber, mediaitem.FieldParentIndexNumber:
			values[i] = new(sql.NullInt64)
		case mediaitem.FieldKind, mediaitem.FieldName, mediaitem.FieldSortName, mediaitem.FieldPath, mediaitem.FieldContainer, mediaitem.FieldOverview, mediaitem.FieldAlbumArtist, mediaitem.FieldImagePath:
			values[i] = new(sql.NullString)
		case mediaitem.FieldID:
			values[i] = new(uuid.UUID)
		case mediaitem.ForeignKeys[0]: // library_items
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case mediaitem.ForeignKeys[1]: // media_item_children
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaItem fields.
func (_m *MediaItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediaitem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case mediaitem.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = mediaitem.Kind(value.String)
			}
		case mediaitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case mediaitem.FieldSortName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sort_name", values[i])
			} else if value.Valid {
				_m.SortName = value.String
			}
		case mediaitem.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case mediaitem.FieldContainer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field container", values[i])
			} else if value.Valid {
				_m.Container = value.String
			}
		case mediaitem.FieldRunTimeTicks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field run_time_ticks", values[i])
			} else if value.Valid {
				_m.RunTimeTicks = value.Int64
			}
		case mediaitem.FieldProductionYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field production_year", values[i])
			} else if value.Valid {
				_m.ProductionYear = new(int32)
				*_m.ProductionYear = int32(value.Int64)
			}
		case mediaitem.FieldIndexNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index_number", values[i])
			} else if value.Valid {
				_m.IndexNumber = new(int32)
				*_m.IndexNumber = int32(value.Int64)
			}
		case mediaitem.FieldParentIndexNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_index_number", values[i])
			} else if value.Valid {
				_m.ParentIndexNumber = new(int32)
				*_m.ParentIndexNumber = int32(value.Int64)
			}
		case mediaitem.FieldOverview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overview", values[i])
			} else if value.Valid {
				_m.Overview = value.String
			}
		case mediaitem.FieldAlbumArtist:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field album_artist", values[i])
			} else if value.Valid {
				_m.AlbumArtist = value.String
			}
		case mediaitem.FieldImagePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_path", values[i])
			} else if value.Valid {
				_m.ImagePath = value.String
			}
		case mediaitem.FieldMediaStreams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field media_streams", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MediaStreams); err != nil {
					return fmt.Errorf("unmarshal field media_streams: %w", err)
				}
			}
		case mediaitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field library_items", values[i])
			} else if value.Valid {
				_m.library_items = new(uuid.UUID)
				*_m.library_items = *value.S.(*uuid.UUID)
			}
		case mediaitem.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field media_item_children", values[i])
			} else if value.Valid {
				_m.media_item_children = new(uuid.UUID)
				*_m.media_item_children = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaItem.
// This includes values selected through modifiers, order, etc.
func (_m *MediaItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLibrary queries the "library" edge of the MediaItem entity.
func (_m *MediaItem) QueryLibrary() *LibraryQuery {
	return NewMediaItemClient(_m.config).QueryLibrary(_m)
}

// QueryParent queries the "parent" edge of the MediaItem entity.
func (_m *MediaItem) QueryParent() *MediaItemQuery {
	return NewMediaItemClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the MediaItem entity.
func (_m *MediaItem) QueryChildren() *MediaItemQuery {
	return NewMediaItemClient(_m.config).QueryChildren(_m)
}

// QueryPlaystates queries the "playstates" edge of the MediaItem entity.
func (_m *MediaItem) QueryPlaystates() *PlayStateQuery {
	return NewMediaItemClient(_m.config).QueryPlaystates(_m)
}

// Update returns a builder for updating this MediaItem.
// Note that you need to call MediaItem.Unwrap() before calling this method if this MediaItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaItem) Update() *MediaItemUpdateOne {
	return NewMediaItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaItem) Unwrap() *MediaItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaItem) String() string {
	var builder strings.Builder
	builder.WriteString("MediaItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("sort_name=")
	builder.WriteString(_m.SortName)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("container=")
	builder.WriteString(_m.Container)
	builder.WriteString(", ")
	builder.WriteString("run_time_ticks=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunTimeTicks))
	builder.WriteString(", ")
	if v := _m.ProductionYear; v != nil {
		builder.WriteString("production_year=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IndexNumber; v != nil {
		builder.WriteString("index_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ParentIndexNumber; v != nil {
		builder.WriteString("parent_index_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("overview=")
	builder.WriteString(_m.Overview)
	builder.WriteString(", ")
	builder.WriteString("album_artist=")
	builder.WriteString(_m.AlbumArtist)
	builder.WriteString(", ")
	builder.WriteString("image_path=")
	builder.WriteString(_m.ImagePath)
	builder.WriteString(", ")
	builder.WriteString("media_streams=")
	builder.WriteString(fmt.Sprintf("%v", _m.MediaStreams))
	builder.WriteByte(')')
	return builder.String()
}

// MediaItems is a parsable slice of MediaItem.
type MediaItems []*MediaItem
