// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/library"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/ent/playstate"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/gartnera/gofin/internal/nfo"
	"github.com/gartnera/gofin/internal/probe"
	"github.com/google/uuid"
)

// MediaItemUpdate is the builder for updating MediaItem entities.
type MediaItemUpdate struct {
	config
	hooks    []Hook
	mutation *MediaItemMutation
}

// Where appends a list predicates to the MediaItemUpdate builder.
func (_u *MediaItemUpdate) Where(ps ...predicate.MediaItem) *MediaItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *MediaItemUpdate) SetKind(v mediaitem.Kind) *MediaItemUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableKind(v *mediaitem.Kind) *MediaItemUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MediaItemUpdate) SetName(v string) *MediaItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableName(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *MediaItemUpdate) SetSortName(v string) *MediaItemUpdate {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableSortName(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *MediaItemUpdate) SetPath(v string) *MediaItemUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillablePath(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMtime sets the "mtime" field.
func (_u *MediaItemUpdate) SetMtime(v int64) *MediaItemUpdate {
	_u.mutation.ResetMtime()
	_u.mutation.SetMtime(v)
	return _u
}

// SetNillableMtime sets the "mtime" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableMtime(v *int64) *MediaItemUpdate {
	if v != nil {
		_u.SetMtime(*v)
	}
	return _u
}

// AddMtime adds value to the "mtime" field.
func (_u *MediaItemUpdate) AddMtime(v int64) *MediaItemUpdate {
	_u.mutation.AddMtime(v)
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaItemUpdate) SetSize(v int64) *MediaItemUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableSize(v *int64) *MediaItemUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaItemUpdate) AddSize(v int64) *MediaItemUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetContainer sets the "container" field.
func (_u *MediaItemUpdate) SetContainer(v string) *MediaItemUpdate {
	_u.mutation.SetContainer(v)
	return _u
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableContainer(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetContainer(*v)
	}
	return _u
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (_u *MediaItemUpdate) SetRunTimeTicks(v int64) *MediaItemUpdate {
	_u.mutation.ResetRunTimeTicks()
	_u.mutation.SetRunTimeTicks(v)
	return _u
}

// SetNillableRunTimeTicks sets the "run_time_ticks" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableRunTimeTicks(v *int64) *MediaItemUpdate {
	if v != nil {
		_u.SetRunTimeTicks(*v)
	}
	return _u
}

// AddRunTimeTicks adds value to the "run_time_ticks" field.
func (_u *MediaItemUpdate) AddRunTimeTicks(v int64) *MediaItemUpdate {
	_u.mutation.AddRunTimeTicks(v)
	return _u
}

// SetProductionYear sets the "production_year" field.
func (_u *MediaItemUpdate) SetProductionYear(v int32) *MediaItemUpdate {
	_u.mutation.ResetProductionYear()
	_u.mutation.SetProductionYear(v)
	return _u
}

// SetNillableProductionYear sets the "production_year" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableProductionYear(v *int32) *MediaItemUpdate {
	if v != nil {
		_u.SetProductionYear(*v)
	}
	return _u
}

// AddProductionYear adds value to the "production_year" field.
func (_u *MediaItemUpdate) AddProductionYear(v int32) *MediaItemUpdate {
	_u.mutation.AddProductionYear(v)
	return _u
}

// ClearProductionYear clears the value of the "production_year" field.
func (_u *MediaItemUpdate) ClearProductionYear() *MediaItemUpdate {
	_u.mutation.ClearProductionYear()
	return _u
}

// SetIndexNumber sets the "index_number" field.
func (_u *MediaItemUpdate) SetIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.ResetIndexNumber()
	_u.mutation.SetIndexNumber(v)
	return _u
}

// SetNillableIndexNumber sets the "index_number" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableIndexNumber(v *int32) *MediaItemUpdate {
	if v != nil {
		_u.SetIndexNumber(*v)
	}
	return _u
}

// AddIndexNumber adds value to the "index_number" field.
func (_u *MediaItemUpdate) AddIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.AddIndexNumber(v)
	return _u
}

// ClearIndexNumber clears the value of the "index_number" field.
func (_u *MediaItemUpdate) ClearIndexNumber() *MediaItemUpdate {
	_u.mutation.ClearIndexNumber()
	return _u
}

// SetIndexNumberEnd sets the "index_number_end" field.
func (_u *MediaItemUpdate) SetIndexNumberEnd(v int32) *MediaItemUpdate {
	_u.mutation.ResetIndexNumberEnd()
	_u.mutation.SetIndexNumberEnd(v)
	return _u
}

// SetNillableIndexNumberEnd sets the "index_number_end" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableIndexNumberEnd(v *int32) *MediaItemUpdate {
	if v != nil {
		_u.SetIndexNumberEnd(*v)
	}
	return _u
}

// AddIndexNumberEnd adds value to the "index_number_end" field.
func (_u *MediaItemUpdate) AddIndexNumberEnd(v int32) *MediaItemUpdate {
	_u.mutation.AddIndexNumberEnd(v)
	return _u
}

// ClearIndexNumberEnd clears the value of the "index_number_end" field.
func (_u *MediaItemUpdate) ClearIndexNumberEnd() *MediaItemUpdate {
	_u.mutation.ClearIndexNumberEnd()
	return _u
}

// SetParentIndexNumber sets the "parent_index_number" field.
func (_u *MediaItemUpdate) SetParentIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.ResetParentIndexNumber()
	_u.mutation.SetParentIndexNumber(v)
	return _u
}

// SetNillableParentIndexNumber sets the "parent_index_number" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableParentIndexNumber(v *int32) *MediaItemUpdate {
	if v != nil {
		_u.SetParentIndexNumber(*v)
	}
	return _u
}

// AddParentIndexNumber adds value to the "parent_index_number" field.
func (_u *MediaItemUpdate) AddParentIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.AddParentIndexNumber(v)
	return _u
}

// ClearParentIndexNumber clears the value of the "parent_index_number" field.
func (_u *MediaItemUpdate) ClearParentIndexNumber() *MediaItemUpdate {
	_u.mutation.ClearParentIndexNumber()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *MediaItemUpdate) SetOverview(v string) *MediaItemUpdate {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableOverview(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// SetTagline sets the "tagline" field.
func (_u *MediaItemUpdate) SetTagline(v string) *MediaItemUpdate {
	_u.mutation.SetTagline(v)
	return _u
}

// SetNillableTagline sets the "tagline" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableTagline(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetTagline(*v)
	}
	return _u
}

// SetOfficialRating sets the "official_rating" field.
func (_u *MediaItemUpdate) SetOfficialRating(v string) *MediaItemUpdate {
	_u.mutation.SetOfficialRating(v)
	return _u
}

// SetNillableOfficialRating sets the "official_rating" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableOfficialRating(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetOfficialRating(*v)
	}
	return _u
}

// SetCommunityRating sets the "community_rating" field.
func (_u *MediaItemUpdate) SetCommunityRating(v float32) *MediaItemUpdate {
	_u.mutation.ResetCommunityRating()
	_u.mutation.SetCommunityRating(v)
	return _u
}

// SetNillableCommunityRating sets the "community_rating" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableCommunityRating(v *float32) *MediaItemUpdate {
	if v != nil {
		_u.SetCommunityRating(*v)
	}
	return _u
}

// AddCommunityRating adds value to the "community_rating" field.
func (_u *MediaItemUpdate) AddCommunityRating(v float32) *MediaItemUpdate {
	_u.mutation.AddCommunityRating(v)
	return _u
}

// ClearCommunityRating clears the value of the "community_rating" field.
func (_u *MediaItemUpdate) ClearCommunityRating() *MediaItemUpdate {
	_u.mutation.ClearCommunityRating()
	return _u
}

// SetPremiereDate sets the "premiere_date" field.
func (_u *MediaItemUpdate) SetPremiereDate(v time.Time) *MediaItemUpdate {
	_u.mutation.SetPremiereDate(v)
	return _u
}

// SetNillablePremiereDate sets the "premiere_date" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillablePremiereDate(v *time.Time) *MediaItemUpdate {
	if v != nil {
		_u.SetPremiereDate(*v)
	}
	return _u
}

// ClearPremiereDate clears the value of the "premiere_date" field.
func (_u *MediaItemUpdate) ClearPremiereDate() *MediaItemUpdate {
	_u.mutation.ClearPremiereDate()
	return _u
}

// SetGenres sets the "genres" field.
func (_u *MediaItemUpdate) SetGenres(v []string) *MediaItemUpdate {
	_u.mutation.SetGenres(v)
	return _u
}

// AppendGenres appends value to the "genres" field.
func (_u *MediaItemUpdate) AppendGenres(v []string) *MediaItemUpdate {
	_u.mutation.AppendGenres(v)
	return _u
}

// ClearGenres clears the value of the "genres" field.
func (_u *MediaItemUpdate) ClearGenres() *MediaItemUpdate {
	_u.mutation.ClearGenres()
	return _u
}

// SetStudios sets the "studios" field.
func (_u *MediaItemUpdate) SetStudios(v []string) *MediaItemUpdate {
	_u.mutation.SetStudios(v)
	return _u
}

// AppendStudios appends value to the "studios" field.
func (_u *MediaItemUpdate) AppendStudios(v []string) *MediaItemUpdate {
	_u.mutation.AppendStudios(v)
	return _u
}

// ClearStudios clears the value of the "studios" field.
func (_u *MediaItemUpdate) ClearStudios() *MediaItemUpdate {
	_u.mutation.ClearStudios()
	return _u
}

// SetPeople sets the "people" field.
func (_u *MediaItemUpdate) SetPeople(v []nfo.Person) *MediaItemUpdate {
	_u.mutation.SetPeople(v)
	return _u
}

// AppendPeople appends value to the "people" field.
func (_u *MediaItemUpdate) AppendPeople(v []nfo.Person) *MediaItemUpdate {
	_u.mutation.AppendPeople(v)
	return _u
}

// ClearPeople clears the value of the "people" field.
func (_u *MediaItemUpdate) ClearPeople() *MediaItemUpdate {
	_u.mutation.ClearPeople()
	return _u
}

// SetAlbumArtist sets the "album_artist" field.
func (_u *MediaItemUpdate) SetAlbumArtist(v string) *MediaItemUpdate {
	_u.mutation.SetAlbumArtist(v)
	return _u
}

// SetNillableAlbumArtist sets the "album_artist" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableAlbumArtist(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetAlbumArtist(*v)
	}
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *MediaItemUpdate) SetImagePath(v string) *MediaItemUpdate {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableImagePath(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// SetMediaStreams sets the "media_streams" field.
func (_u *MediaItemUpdate) SetMediaStreams(v []probe.Stream) *MediaItemUpdate {
	_u.mutation.SetMediaStreams(v)
	return _u
}

// AppendMediaStreams appends value to the "media_streams" field.
func (_u *MediaItemUpdate) AppendMediaStreams(v []probe.Stream) *MediaItemUpdate {
	_u.mutation.AppendMediaStreams(v)
	return _u
}

// ClearMediaStreams clears the value of the "media_streams" field.
func (_u *MediaItemUpdate) ClearMediaStreams() *MediaItemUpdate {
	_u.mutation.ClearMediaStreams()
	return _u
}

// SetLibraryID sets the "library" edge to the Library entity by ID.
func (_u *MediaItemUpdate) SetLibraryID(id uuid.UUID) *MediaItemUpdate {
	_u.mutation.SetLibraryID(id)
	return _u
}

// SetNillableLibraryID sets the "library" edge to the Library entity by ID if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableLibraryID(id *uuid.UUID) *MediaItemUpdate {
	if id != nil {
		_u = _u.SetLibraryID(*id)
	}
	return _u
}

// SetLibrary sets the "library" edge to the Library entity.
func (_u *MediaItemUpdate) SetLibrary(v *Library) *MediaItemUpdate {
	return _u.SetLibraryID(v.ID)
}

// SetParentID sets the "parent" edge to the MediaItem entity by ID.
func (_u *MediaItemUpdate) SetParentID(id uuid.UUID) *MediaItemUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the MediaItem entity by ID if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableParentID(id *uuid.UUID) *MediaItemUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdate) SetParent(v *MediaItem) *MediaItemUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the MediaItem entity by IDs.
func (_u *MediaItemUpdate) AddChildIDs(ids ...uuid.UUID) *MediaItemUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the MediaItem entity.
func (_u *MediaItemUpdate) AddChildren(v ...*MediaItem) *MediaItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddPlaystateIDs adds the "playstates" edge to the PlayState entity by IDs.
func (_u *MediaItemUpdate) AddPlaystateIDs(ids ...uuid.UUID) *MediaItemUpdate {
	_u.mutation.AddPlaystateIDs(ids...)
	return _u
}

// AddPlaystates adds the "playstates" edges to the PlayState entity.
func (_u *MediaItemUpdate) AddPlaystates(v ...*PlayState) *MediaItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaystateIDs(ids...)
}

// Mutation returns the MediaItemMutation object of the builder.
func (_u *MediaItemUpdate) Mutation() *MediaItemMutation {
	return _u.mutation
}

// ClearLibrary clears the "library" edge to the Library entity.
func (_u *MediaItemUpdate) ClearLibrary() *MediaItemUpdate {
	_u.mutation.ClearLibrary()
	return _u
}

// ClearParent clears the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdate) ClearParent() *MediaItemUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the MediaItem entity.
func (_u *MediaItemUpdate) ClearChildren() *MediaItemUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to MediaItem entities by IDs.
func (_u *MediaItemUpdate) RemoveChildIDs(ids ...uuid.UUID) *MediaItemUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to MediaItem entities.
func (_u *MediaItemUpdate) RemoveChildren(v ...*MediaItem) *MediaItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearPlaystates clears all "playstates" edges to the PlayState entity.
func (_u *MediaItemUpdate) ClearPlaystates() *MediaItemUpdate {
	_u.mutation.ClearPlaystates()
	return _u
}

// RemovePlaystateIDs removes the "playstates" edge to PlayState entities by IDs.
func (_u *MediaItemUpdate) RemovePlaystateIDs(ids ...uuid.UUID) *MediaItemUpdate {
	_u.mutation.RemovePlaystateIDs(ids...)
	return _u
}

// RemovePlaystates removes "playstates" edges to PlayState entities.
func (_u *MediaItemUpdate) RemovePlaystates(v ...*PlayState) *MediaItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaystateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaItemUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := mediaitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaItem.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mediaitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaItem.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaitem.Table, mediaitem.Columns, sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(mediaitem.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mediaitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(mediaitem.FieldSortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(mediaitem.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mtime(); ok {
		_spec.SetField(mediaitem.FieldMtime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMtime(); ok {
		_spec.AddField(mediaitem.FieldMtime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(mediaitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(mediaitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Container(); ok {
		_spec.SetField(mediaitem.FieldContainer, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunTimeTicks(); ok {
		_spec.SetField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRunTimeTicks(); ok {
		_spec.AddField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductionYear(); ok {
		_spec.SetField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedProductionYear(); ok {
		_spec.AddField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if _u.mutation.ProductionYearCleared() {
		_spec.ClearField(mediaitem.FieldProductionYear, field.TypeInt32)
	}
	if value, ok := _u.mutation.IndexNumber(); ok {
		_spec.SetField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.IndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.IndexNumberEnd(); ok {
		_spec.SetField(mediaitem.FieldIndexNumberEnd, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIndexNumberEnd(); ok {
		_spec.AddField(mediaitem.FieldIndexNumberEnd, field.TypeInt32, value)
	}
	if _u.mutation.IndexNumberEndCleared() {
		_spec.ClearField(mediaitem.FieldIndexNumberEnd, field.TypeInt32)
	}
	if value, ok := _u.mutation.ParentIndexNumber(); ok {
		_spec.SetField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedParentIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.ParentIndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldParentIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(mediaitem.FieldOverview, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tagline(); ok {
		_spec.SetField(mediaitem.FieldTagline, field.TypeString, value)
	}
	if value, ok := _u.mutation.OfficialRating(); ok {
		_spec.SetField(mediaitem.FieldOfficialRating, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommunityRating(); ok {
		_spec.SetField(mediaitem.FieldCommunityRating, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedCommunityRating(); ok {
		_spec.AddField(mediaitem.FieldCommunityRating, field.TypeFloat32, value)
	}
	if _u.mutation.CommunityRatingCleared() {
		_spec.ClearField(mediaitem.FieldCommunityRating, field.TypeFloat32)
	}
	if value, ok := _u.mutation.PremiereDate(); ok {
		_spec.SetField(mediaitem.FieldPremiereDate, field.TypeTime, value)
	}
	if _u.mutation.PremiereDateCleared() {
		_spec.ClearField(mediaitem.FieldPremiereDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Genres(); ok {
		_spec.SetField(mediaitem.FieldGenres, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenres(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldGenres, value)
		})
	}
	if _u.mutation.GenresCleared() {
		_spec.ClearField(mediaitem.FieldGenres, field.TypeJSON)
	}
	if value, ok := _u.mutation.Studios(); ok {
		_spec.SetField(mediaitem.FieldStudios, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStudios(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldStudios, value)
		})
	}
	if _u.mutation.StudiosCleared() {
		_spec.ClearField(mediaitem.FieldStudios, field.TypeJSON)
	}
	if value, ok := _u.mutation.People(); ok {
		_spec.SetField(mediaitem.FieldPeople, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPeople(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldPeople, value)
		})
	}
	if _u.mutation.PeopleCleared() {
		_spec.ClearField(mediaitem.FieldPeople, field.TypeJSON)
	}
	if value, ok := _u.mutation.AlbumArtist(); ok {
		_spec.SetField(mediaitem.FieldAlbumArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(mediaitem.FieldImagePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaStreams(); ok {
		_spec.SetField(mediaitem.FieldMediaStreams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMediaStreams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldMediaStreams, value)
		})
	}
	if _u.mutation.MediaStreamsCleared() {
		_spec.ClearField(mediaitem.FieldMediaStreams, field.TypeJSON)
	}
	if _u.mutation.LibraryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibraryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaystatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.PlaystatesTable,
			Columns: []string{mediaitem.PlaystatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaystatesIDs(); len(nodes) > 0 && !_u.mutation.PlaystatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.PlaystatesTable,
			Columns: []string{mediaitem.PlaystatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaystatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.PlaystatesTable,
			Columns: []string{mediaitem.PlaystatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaItemUpdateOne is the builder for updating a single MediaItem entity.
type MediaItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaItemMutation
}

// SetKind sets the "kind" field.
func (_u *MediaItemUpdateOne) SetKind(v mediaitem.Kind) *MediaItemUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableKind(v *mediaitem.Kind) *MediaItemUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MediaItemUpdateOne) SetName(v string) *MediaItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableName(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *MediaItemUpdateOne) SetSortName(v string) *MediaItemUpdateOne {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableSortName(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *MediaItemUpdateOne) SetPath(v string) *MediaItemUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillablePath(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMtime sets the "mtime" field.
func (_u *MediaItemUpdateOne) SetMtime(v int64) *MediaItemUpdateOne {
	_u.mutation.ResetMtime()
	_u.mutation.SetMtime(v)
	return _u
}

// SetNillableMtime sets the "mtime" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableMtime(v *int64) *MediaItemUpdateOne {
	if v != nil {
		_u.SetMtime(*v)
	}
	return _u
}

// AddMtime adds value to the "mtime" field.
func (_u *MediaItemUpdateOne) AddMtime(v int64) *MediaItemUpdateOne {
	_u.mutation.AddMtime(v)
	return _u
}

// SetSize sets the "size" field.
func (_u *MediaItemUpdateOne) SetSize(v int64) *MediaItemUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableSize(v *int64) *MediaItemUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *MediaItemUpdateOne) AddSize(v int64) *MediaItemUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetContainer sets the "container" field.
func (_u *MediaItemUpdateOne) SetContainer(v string) *MediaItemUpdateOne {
	_u.mutation.SetContainer(v)
	return _u
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableContainer(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetContainer(*v)
	}
	return _u
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (_u *MediaItemUpdateOne) SetRunTimeTicks(v int64) *MediaItemUpdateOne {
	_u.mutation.ResetRunTimeTicks()
	_u.mutation.SetRunTimeTicks(v)
	return _u
}

// SetNillableRunTimeTicks sets the "run_time_ticks" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableRunTimeTicks(v *int64) *MediaItemUpdateOne {
	if v != nil {
		_u.SetRunTimeTicks(*v)
	}
	return _u
}

// AddRunTimeTicks adds value to the "run_time_ticks" field.
func (_u *MediaItemUpdateOne) AddRunTimeTicks(v int64) *MediaItemUpdateOne {
	_u.mutation.AddRunTimeTicks(v)
	return _u
}

// SetProductionYear sets the "production_year" field.
func (_u *MediaItemUpdateOne) SetProductionYear(v int32) *MediaItemUpdateOne {
	_u.mutation.ResetProductionYear()
	_u.mutation.SetProductionYear(v)
	return _u
}

// SetNillableProductionYear sets the "production_year" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableProductionYear(v *int32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetProductionYear(*v)
	}
	return _u
}

// AddProductionYear adds value to the "production_year" field.
func (_u *MediaItemUpdateOne) AddProductionYear(v int32) *MediaItemUpdateOne {
	_u.mutation.AddProductionYear(v)
	return _u
}

// ClearProductionYear clears the value of the "production_year" field.
func (_u *MediaItemUpdateOne) ClearProductionYear() *MediaItemUpdateOne {
	_u.mutation.ClearProductionYear()
	return _u
}

// SetIndexNumber sets the "index_number" field.
func (_u *MediaItemUpdateOne) SetIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.ResetIndexNumber()
	_u.mutation.SetIndexNumber(v)
	return _u
}

// SetNillableIndexNumber sets the "index_number" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableIndexNumber(v *int32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetIndexNumber(*v)
	}
	return _u
}

// AddIndexNumber adds value to the "index_number" field.
func (_u *MediaItemUpdateOne) AddIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.AddIndexNumber(v)
	return _u
}

// ClearIndexNumber clears the value of the "index_number" field.
func (_u *MediaItemUpdateOne) ClearIndexNumber() *MediaItemUpdateOne {
	_u.mutation.ClearIndexNumber()
	return _u
}

// SetIndexNumberEnd sets the "index_number_end" field.
func (_u *MediaItemUpdateOne) SetIndexNumberEnd(v int32) *MediaItemUpdateOne {
	_u.mutation.ResetIndexNumberEnd()
	_u.mutation.SetIndexNumberEnd(v)
	return _u
}

// SetNillableIndexNumberEnd sets the "index_number_end" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableIndexNumberEnd(v *int32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetIndexNumberEnd(*v)
	}
	return _u
}

// AddIndexNumberEnd adds value to the "index_number_end" field.
func (_u *MediaItemUpdateOne) AddIndexNumberEnd(v int32) *MediaItemUpdateOne {
	_u.mutation.AddIndexNumberEnd(v)
	return _u
}

// ClearIndexNumberEnd clears the value of the "index_number_end" field.
func (_u *MediaItemUpdateOne) ClearIndexNumberEnd() *MediaItemUpdateOne {
	_u.mutation.ClearIndexNumberEnd()
	return _u
}

// SetParentIndexNumber sets the "parent_index_number" field.
func (_u *MediaItemUpdateOne) SetParentIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.ResetParentIndexNumber()
	_u.mutation.SetParentIndexNumber(v)
	return _u
}

// SetNillableParentIndexNumber sets the "parent_index_number" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableParentIndexNumber(v *int32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetParentIndexNumber(*v)
	}
	return _u
}

// AddParentIndexNumber adds value to the "parent_index_number" field.
func (_u *MediaItemUpdateOne) AddParentIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.AddParentIndexNumber(v)
	return _u
}

// ClearParentIndexNumber clears the value of the "parent_index_number" field.
func (_u *MediaItemUpdateOne) ClearParentIndexNumber() *MediaItemUpdateOne {
	_u.mutation.ClearParentIndexNumber()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *MediaItemUpdateOne) SetOverview(v string) *MediaItemUpdateOne {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableOverview(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// SetTagline sets the "tagline" field.
func (_u *MediaItemUpdateOne) SetTagline(v string) *MediaItemUpdateOne {
	_u.mutation.SetTagline(v)
	return _u
}

// SetNillableTagline sets the "tagline" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableTagline(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetTagline(*v)
	}
	return _u
}

// SetOfficialRating sets the "official_rating" field.
func (_u *MediaItemUpdateOne) SetOfficialRating(v string) *MediaItemUpdateOne {
	_u.mutation.SetOfficialRating(v)
	return _u
}

// SetNillableOfficialRating sets the "official_rating" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableOfficialRating(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetOfficialRating(*v)
	}
	return _u
}

// SetCommunityRating sets the "community_rating" field.
func (_u *MediaItemUpdateOne) SetCommunityRating(v float32) *MediaItemUpdateOne {
	_u.mutation.ResetCommunityRating()
	_u.mutation.SetCommunityRating(v)
	return _u
}

// SetNillableCommunityRating sets the "community_rating" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableCommunityRating(v *float32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetCommunityRating(*v)
	}
	return _u
}

// AddCommunityRating adds value to the "community_rating" field.
func (_u *MediaItemUpdateOne) AddCommunityRating(v float32) *MediaItemUpdateOne {
	_u.mutation.AddCommunityRating(v)
	return _u
}

// ClearCommunityRating clears the value of the "community_rating" field.
func (_u *MediaItemUpdateOne) ClearCommunityRating() *MediaItemUpdateOne {
	_u.mutation.ClearCommunityRating()
	return _u
}

// SetPremiereDate sets the "premiere_date" field.
func (_u *MediaItemUpdateOne) SetPremiereDate(v time.Time) *MediaItemUpdateOne {
	_u.mutation.SetPremiereDate(v)
	return _u
}

// SetNillablePremiereDate sets the "premiere_date" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillablePremiereDate(v *time.Time) *MediaItemUpdateOne {
	if v != nil {
		_u.SetPremiereDate(*v)
	}
	return _u
}

// ClearPremiereDate clears the value of the "premiere_date" field.
func (_u *MediaItemUpdateOne) ClearPremiereDate() *MediaItemUpdateOne {
	_u.mutation.ClearPremiereDate()
	return _u
}

// SetGenres sets the "genres" field.
func (_u *MediaItemUpdateOne) SetGenres(v []string) *MediaItemUpdateOne {
	_u.mutation.SetGenres(v)
	return _u
}

// AppendGenres appends value to the "genres" field.
func (_u *MediaItemUpdateOne) AppendGenres(v []string) *MediaItemUpdateOne {
	_u.mutation.AppendGenres(v)
	return _u
}

// ClearGenres clears the value of the "genres" field.
func (_u *MediaItemUpdateOne) ClearGenres() *MediaItemUpdateOne {
	_u.mutation.ClearGenres()
	return _u
}

// SetStudios sets the "studios" field.
func (_u *MediaItemUpdateOne) SetStudios(v []string) *MediaItemUpdateOne {
	_u.mutation.SetStudios(v)
	return _u
}

// AppendStudios appends value to the "studios" field.
func (_u *MediaItemUpdateOne) AppendStudios(v []string) *MediaItemUpdateOne {
	_u.mutation.AppendStudios(v)
	return _u
}

// ClearStudios clears the value of the "studios" field.
func (_u *MediaItemUpdateOne) ClearStudios() *MediaItemUpdateOne {
	_u.mutation.ClearStudios()
	return _u
}

// SetPeople sets the "people" field.
func (_u *MediaItemUpdateOne) SetPeople(v []nfo.Person) *MediaItemUpdateOne {
	_u.mutation.SetPeople(v)
	return _u
}

// AppendPeople appends value to the "people" field.
func (_u *MediaItemUpdateOne) AppendPeople(v []nfo.Person) *MediaItemUpdateOne {
	_u.mutation.AppendPeople(v)
	return _u
}

// ClearPeople clears the value of the "people" field.
func (_u *MediaItemUpdateOne) ClearPeople() *MediaItemUpdateOne {
	_u.mutation.ClearPeople()
	return _u
}

// SetAlbumArtist sets the "album_artist" field.
func (_u *MediaItemUpdateOne) SetAlbumArtist(v string) *MediaItemUpdateOne {
	_u.mutation.SetAlbumArtist(v)
	return _u
}

// SetNillableAlbumArtist sets the "album_artist" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableAlbumArtist(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetAlbumArtist(*v)
	}
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *MediaItemUpdateOne) SetImagePath(v string) *MediaItemUpdateOne {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableImagePath(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// SetMediaStreams sets the "media_streams" field.
func (_u *MediaItemUpdateOne) SetMediaStreams(v []probe.Stream) *MediaItemUpdateOne {
	_u.mutation.SetMediaStreams(v)
	return _u
}

// AppendMediaStreams appends value to the "media_streams" field.
func (_u *MediaItemUpdateOne) AppendMediaStreams(v []probe.Stream) *MediaItemUpdateOne {
	_u.mutation.AppendMediaStreams(v)
	return _u
}

// ClearMediaStreams clears the value of the "media_streams" field.
func (_u *MediaItemUpdateOne) ClearMediaStreams() *MediaItemUpdateOne {
	_u.mutation.ClearMediaStreams()
	return _u
}

// SetLibraryID sets the "library" edge to the Library entity by ID.
func (_u *MediaItemUpdateOne) SetLibraryID(id uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.SetLibraryID(id)
	return _u
}

// SetNillableLibraryID sets the "library" edge to the Library entity by ID if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableLibraryID(id *uuid.UUID) *MediaItemUpdateOne {
	if id != nil {
		_u = _u.SetLibraryID(*id)
	}
	return _u
}

// SetLibrary sets the "library" edge to the Library entity.
func (_u *MediaItemUpdateOne) SetLibrary(v *Library) *MediaItemUpdateOne {
	return _u.SetLibraryID(v.ID)
}

// SetParentID sets the "parent" edge to the MediaItem entity by ID.
func (_u *MediaItemUpdateOne) SetParentID(id uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the MediaItem entity by ID if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableParentID(id *uuid.UUID) *MediaItemUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdateOne) SetParent(v *MediaItem) *MediaItemUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the MediaItem entity by IDs.
func (_u *MediaItemUpdateOne) AddChildIDs(ids ...uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the MediaItem entity.
func (_u *MediaItemUpdateOne) AddChildren(v ...*MediaItem) *MediaItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddPlaystateIDs adds the "playstates" edge to the PlayState entity by IDs.
func (_u *MediaItemUpdateOne) AddPlaystateIDs(ids ...uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.AddPlaystateIDs(ids...)
	return _u
}

// AddPlaystates adds the "playstates" edges to the PlayState entity.
func (_u *MediaItemUpdateOne) AddPlaystates(v ...*PlayState) *MediaItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaystateIDs(ids...)
}

// Mutation returns the MediaItemMutation object of the builder.
func (_u *MediaItemUpdateOne) Mutation() *MediaItemMutation {
	return _u.mutation
}

// ClearLibrary clears the "library" edge to the Library entity.
func (_u *MediaItemUpdateOne) ClearLibrary() *MediaItemUpdateOne {
	_u.mutation.ClearLibrary()
	return _u
}

// ClearParent clears the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdateOne) ClearParent() *MediaItemUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the MediaItem entity.
func (_u *MediaItemUpdateOne) ClearChildren() *MediaItemUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to MediaItem entities by IDs.
func (_u *MediaItemUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to MediaItem entities.
func (_u *MediaItemUpdateOne) RemoveChildren(v ...*MediaItem) *MediaItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearPlaystates clears all "playstates" edges to the PlayState entity.
func (_u *MediaItemUpdateOne) ClearPlaystates() *MediaItemUpdateOne {
	_u.mutation.ClearPlaystates()
	return _u
}

// RemovePlaystateIDs removes the "playstates" edge to PlayState entities by IDs.
func (_u *MediaItemUpdateOne) RemovePlaystateIDs(ids ...uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.RemovePlaystateIDs(ids...)
	return _u
}

// RemovePlaystates removes "playstates" edges to PlayState entities.
func (_u *MediaItemUpdateOne) RemovePlaystates(v ...*PlayState) *MediaItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaystateIDs(ids...)
}

// Where appends a list predicates to the MediaItemUpdate builder.
func (_u *MediaItemUpdateOne) Where(ps ...predicate.MediaItem) *MediaItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaItemUpdateOne) Select(field string, fields ...string) *MediaItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaItem entity.
func (_u *MediaItemUpdateOne) Save(ctx context.Context) (*MediaItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaItemUpdateOne) SaveX(ctx context.Context) *MediaItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaItemUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := mediaitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaItem.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mediaitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaItem.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaItemUpdateOne) sqlSave(ctx context.Context) (_node *MediaItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaitem.Table, mediaitem.Columns, sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaitem.FieldID)
		for _, f := range fields {
			if !mediaitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(mediaitem.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mediaitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(mediaitem.FieldSortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(mediaitem.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mtime(); ok {
		_spec.SetField(mediaitem.FieldMtime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMtime(); ok {
		_spec.AddField(mediaitem.FieldMtime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(mediaitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(mediaitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Container(); ok {
		_spec.SetField(mediaitem.FieldContainer, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunTimeTicks(); ok {
		_spec.SetField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRunTimeTicks(); ok {
		_spec.AddField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductionYear(); ok {
		_spec.SetField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedProductionYear(); ok {
		_spec.AddField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if _u.mutation.ProductionYearCleared() {
		_spec.ClearField(mediaitem.FieldProductionYear, field.TypeInt32)
	}
	if value, ok := _u.mutation.IndexNumber(); ok {
		_spec.SetField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.IndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.IndexNumberEnd(); ok {
		_spec.SetField(mediaitem.FieldIndexNumberEnd, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIndexNumberEnd(); ok {
		_spec.AddField(mediaitem.FieldIndexNumberEnd, field.TypeInt32, value)
	}
	if _u.mutation.IndexNumberEndCleared() {
		_spec.ClearField(mediaitem.FieldIndexNumberEnd, field.TypeInt32)
	}
	if value, ok := _u.mutation.ParentIndexNumber(); ok {
		_spec.SetField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedParentIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.ParentIndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldParentIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(mediaitem.FieldOverview, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tagline(); ok {
		_spec.SetField(mediaitem.FieldTagline, field.TypeString, value)
	}
	if value, ok := _u.mutation.OfficialRating(); ok {
		_spec.SetField(mediaitem.FieldOfficialRating, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommunityRating(); ok {
		_spec.SetField(mediaitem.FieldCommunityRating, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedCommunityRating(); ok {
		_spec.AddField(mediaitem.FieldCommunityRating, field.TypeFloat32, value)
	}
	if _u.mutation.CommunityRatingCleared() {
		_spec.ClearField(mediaitem.FieldCommunityRating, field.TypeFloat32)
	}
	if value, ok := _u.mutation.PremiereDate(); ok {
		_spec.SetField(mediaitem.FieldPremiereDate, field.TypeTime, value)
	}
	if _u.mutation.PremiereDateCleared() {
		_spec.ClearField(mediaitem.FieldPremiereDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Genres(); ok {
		_spec.SetField(mediaitem.FieldGenres, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenres(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldGenres, value)
		})
	}
	if _u.mutation.GenresCleared() {
		_spec.ClearField(mediaitem.FieldGenres, field.TypeJSON)
	}
	if value, ok := _u.mutation.Studios(); ok {
		_spec.SetField(mediaitem.FieldStudios, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStudios(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldStudios, value)
		})
	}
	if _u.mutation.StudiosCleared() {
		_spec.ClearField(mediaitem.FieldStudios, field.TypeJSON)
	}
	if value, ok := _u.mutation.People(); ok {
		_spec.SetField(mediaitem.FieldPeople, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPeople(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldPeople, value)
		})
	}
	if _u.mutation.PeopleCleared() {
		_spec.ClearField(mediaitem.FieldPeople, field.TypeJSON)
	}
	if value, ok := _u.mutation.AlbumArtist(); ok {
		_spec.SetField(mediaitem.FieldAlbumArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(mediaitem.FieldImagePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaStreams(); ok {
		_spec.SetField(mediaitem.FieldMediaStreams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMediaStreams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaitem.FieldMediaStreams, value)
		})
	}
	if _u.mutation.MediaStreamsCleared() {
		_spec.ClearField(mediaitem.FieldMediaStreams, field.TypeJSON)
	}
	if _u.mutation.LibraryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibraryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaystatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.PlaystatesTable,
			Columns: []string{mediaitem.PlaystatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaystatesIDs(); len(nodes) > 0 && !_u.mutation.PlaystatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.PlaystatesTable,
			Columns: []string{mediaitem.PlaystatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaystatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.PlaystatesTable,
			Columns: []string{mediaitem.PlaystatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
