// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/library"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/google/uuid"
)

// MediaItemUpdate is the builder for updating MediaItem entities.
type MediaItemUpdate struct {
	config
	hooks    []Hook
	mutation *MediaItemMutation
}

// Where appends a list predicates to the MediaItemUpdate builder.
func (_u *MediaItemUpdate) Where(ps ...predicate.MediaItem) *MediaItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *MediaItemUpdate) SetKind(v mediaitem.Kind) *MediaItemUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableKind(v *mediaitem.Kind) *MediaItemUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MediaItemUpdate) SetName(v string) *MediaItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableName(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *MediaItemUpdate) SetSortName(v string) *MediaItemUpdate {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableSortName(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *MediaItemUpdate) SetPath(v string) *MediaItemUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillablePath(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetContainer sets the "container" field.
func (_u *MediaItemUpdate) SetContainer(v string) *MediaItemUpdate {
	_u.mutation.SetContainer(v)
	return _u
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableContainer(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetContainer(*v)
	}
	return _u
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (_u *MediaItemUpdate) SetRunTimeTicks(v int64) *MediaItemUpdate {
	_u.mutation.ResetRunTimeTicks()
	_u.mutation.SetRunTimeTicks(v)
	return _u
}

// SetNillableRunTimeTicks sets the "run_time_ticks" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableRunTimeTicks(v *int64) *MediaItemUpdate {
	if v != nil {
		_u.SetRunTimeTicks(*v)
	}
	return _u
}

// AddRunTimeTicks adds value to the "run_time_ticks" field.
func (_u *MediaItemUpdate) AddRunTimeTicks(v int64) *MediaItemUpdate {
	_u.mutation.AddRunTimeTicks(v)
	return _u
}

// SetProductionYear sets the "production_year" field.
func (_u *MediaItemUpdate) SetProductionYear(v int32) *MediaItemUpdate {
	_u.mutation.ResetProductionYear()
	_u.mutation.SetProductionYear(v)
	return _u
}

// SetNillableProductionYear sets the "production_year" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableProductionYear(v *int32) *MediaItemUpdate {
	if v != nil {
		_u.SetProductionYear(*v)
	}
	return _u
}

// AddProductionYear adds value to the "production_year" field.
func (_u *MediaItemUpdate) AddProductionYear(v int32) *MediaItemUpdate {
	_u.mutation.AddProductionYear(v)
	return _u
}

// ClearProductionYear clears the value of the "production_year" field.
func (_u *MediaItemUpdate) ClearProductionYear() *MediaItemUpdate {
	_u.mutation.ClearProductionYear()
	return _u
}

// SetIndexNumber sets the "index_number" field.
func (_u *MediaItemUpdate) SetIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.ResetIndexNumber()
	_u.mutation.SetIndexNumber(v)
	return _u
}

// SetNillableIndexNumber sets the "index_number" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableIndexNumber(v *int32) *MediaItemUpdate {
	if v != nil {
		_u.SetIndexNumber(*v)
	}
	return _u
}

// AddIndexNumber adds value to the "index_number" field.
func (_u *MediaItemUpdate) AddIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.AddIndexNumber(v)
	return _u
}

// ClearIndexNumber clears the value of the "index_number" field.
func (_u *MediaItemUpdate) ClearIndexNumber() *MediaItemUpdate {
	_u.mutation.ClearIndexNumber()
	return _u
}

// SetParentIndexNumber sets the "parent_index_number" field.
func (_u *MediaItemUpdate) SetParentIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.ResetParentIndexNumber()
	_u.mutation.SetParentIndexNumber(v)
	return _u
}

// SetNillableParentIndexNumber sets the "parent_index_number" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableParentIndexNumber(v *int32) *MediaItemUpdate {
	if v != nil {
		_u.SetParentIndexNumber(*v)
	}
	return _u
}

// AddParentIndexNumber adds value to the "parent_index_number" field.
func (_u *MediaItemUpdate) AddParentIndexNumber(v int32) *MediaItemUpdate {
	_u.mutation.AddParentIndexNumber(v)
	return _u
}

// ClearParentIndexNumber clears the value of the "parent_index_number" field.
func (_u *MediaItemUpdate) ClearParentIndexNumber() *MediaItemUpdate {
	_u.mutation.ClearParentIndexNumber()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *MediaItemUpdate) SetOverview(v string) *MediaItemUpdate {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableOverview(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// SetAlbumArtist sets the "album_artist" field.
func (_u *MediaItemUpdate) SetAlbumArtist(v string) *MediaItemUpdate {
	_u.mutation.SetAlbumArtist(v)
	return _u
}

// SetNillableAlbumArtist sets the "album_artist" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableAlbumArtist(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetAlbumArtist(*v)
	}
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *MediaItemUpdate) SetImagePath(v string) *MediaItemUpdate {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableImagePath(v *string) *MediaItemUpdate {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// SetLibraryID sets the "library" edge to the Library entity by ID.
func (_u *MediaItemUpdate) SetLibraryID(id uuid.UUID) *MediaItemUpdate {
	_u.mutation.SetLibraryID(id)
	return _u
}

// SetNillableLibraryID sets the "library" edge to the Library entity by ID if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableLibraryID(id *uuid.UUID) *MediaItemUpdate {
	if id != nil {
		_u = _u.SetLibraryID(*id)
	}
	return _u
}

// SetLibrary sets the "library" edge to the Library entity.
func (_u *MediaItemUpdate) SetLibrary(v *Library) *MediaItemUpdate {
	return _u.SetLibraryID(v.ID)
}

// SetParentID sets the "parent" edge to the MediaItem entity by ID.
func (_u *MediaItemUpdate) SetParentID(id uuid.UUID) *MediaItemUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the MediaItem entity by ID if the given value is not nil.
func (_u *MediaItemUpdate) SetNillableParentID(id *uuid.UUID) *MediaItemUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdate) SetParent(v *MediaItem) *MediaItemUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the MediaItem entity by IDs.
func (_u *MediaItemUpdate) AddChildIDs(ids ...uuid.UUID) *MediaItemUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the MediaItem entity.
func (_u *MediaItemUpdate) AddChildren(v ...*MediaItem) *MediaItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the MediaItemMutation object of the builder.
func (_u *MediaItemUpdate) Mutation() *MediaItemMutation {
	return _u.mutation
}

// ClearLibrary clears the "library" edge to the Library entity.
func (_u *MediaItemUpdate) ClearLibrary() *MediaItemUpdate {
	_u.mutation.ClearLibrary()
	return _u
}

// ClearParent clears the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdate) ClearParent() *MediaItemUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the MediaItem entity.
func (_u *MediaItemUpdate) ClearChildren() *MediaItemUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to MediaItem entities by IDs.
func (_u *MediaItemUpdate) RemoveChildIDs(ids ...uuid.UUID) *MediaItemUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to MediaItem entities.
func (_u *MediaItemUpdate) RemoveChildren(v ...*MediaItem) *MediaItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaItemUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := mediaitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaItem.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mediaitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaItem.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaitem.Table, mediaitem.Columns, sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(mediaitem.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mediaitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(mediaitem.FieldSortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(mediaitem.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Container(); ok {
		_spec.SetField(mediaitem.FieldContainer, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunTimeTicks(); ok {
		_spec.SetField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRunTimeTicks(); ok {
		_spec.AddField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductionYear(); ok {
		_spec.SetField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedProductionYear(); ok {
		_spec.AddField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if _u.mutation.ProductionYearCleared() {
		_spec.ClearField(mediaitem.FieldProductionYear, field.TypeInt32)
	}
	if value, ok := _u.mutation.IndexNumber(); ok {
		_spec.SetField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.IndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.ParentIndexNumber(); ok {
		_spec.SetField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedParentIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.ParentIndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldParentIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(mediaitem.FieldOverview, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlbumArtist(); ok {
		_spec.SetField(mediaitem.FieldAlbumArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(mediaitem.FieldImagePath, field.TypeString, value)
	}
	if _u.mutation.LibraryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibraryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaItemUpdateOne is the builder for updating a single MediaItem entity.
type MediaItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaItemMutation
}

// SetKind sets the "kind" field.
func (_u *MediaItemUpdateOne) SetKind(v mediaitem.Kind) *MediaItemUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableKind(v *mediaitem.Kind) *MediaItemUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MediaItemUpdateOne) SetName(v string) *MediaItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableName(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *MediaItemUpdateOne) SetSortName(v string) *MediaItemUpdateOne {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableSortName(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *MediaItemUpdateOne) SetPath(v string) *MediaItemUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillablePath(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetContainer sets the "container" field.
func (_u *MediaItemUpdateOne) SetContainer(v string) *MediaItemUpdateOne {
	_u.mutation.SetContainer(v)
	return _u
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableContainer(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetContainer(*v)
	}
	return _u
}

// SetRunTimeTicks sets the "run_time_ticks" field.
func (_u *MediaItemUpdateOne) SetRunTimeTicks(v int64) *MediaItemUpdateOne {
	_u.mutation.ResetRunTimeTicks()
	_u.mutation.SetRunTimeTicks(v)
	return _u
}

// SetNillableRunTimeTicks sets the "run_time_ticks" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableRunTimeTicks(v *int64) *MediaItemUpdateOne {
	if v != nil {
		_u.SetRunTimeTicks(*v)
	}
	return _u
}

// AddRunTimeTicks adds value to the "run_time_ticks" field.
func (_u *MediaItemUpdateOne) AddRunTimeTicks(v int64) *MediaItemUpdateOne {
	_u.mutation.AddRunTimeTicks(v)
	return _u
}

// SetProductionYear sets the "production_year" field.
func (_u *MediaItemUpdateOne) SetProductionYear(v int32) *MediaItemUpdateOne {
	_u.mutation.ResetProductionYear()
	_u.mutation.SetProductionYear(v)
	return _u
}

// SetNillableProductionYear sets the "production_year" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableProductionYear(v *int32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetProductionYear(*v)
	}
	return _u
}

// AddProductionYear adds value to the "production_year" field.
func (_u *MediaItemUpdateOne) AddProductionYear(v int32) *MediaItemUpdateOne {
	_u.mutation.AddProductionYear(v)
	return _u
}

// ClearProductionYear clears the value of the "production_year" field.
func (_u *MediaItemUpdateOne) ClearProductionYear() *MediaItemUpdateOne {
	_u.mutation.ClearProductionYear()
	return _u
}

// SetIndexNumber sets the "index_number" field.
func (_u *MediaItemUpdateOne) SetIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.ResetIndexNumber()
	_u.mutation.SetIndexNumber(v)
	return _u
}

// SetNillableIndexNumber sets the "index_number" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableIndexNumber(v *int32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetIndexNumber(*v)
	}
	return _u
}

// AddIndexNumber adds value to the "index_number" field.
func (_u *MediaItemUpdateOne) AddIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.AddIndexNumber(v)
	return _u
}

// ClearIndexNumber clears the value of the "index_number" field.
func (_u *MediaItemUpdateOne) ClearIndexNumber() *MediaItemUpdateOne {
	_u.mutation.ClearIndexNumber()
	return _u
}

// SetParentIndexNumber sets the "parent_index_number" field.
func (_u *MediaItemUpdateOne) SetParentIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.ResetParentIndexNumber()
	_u.mutation.SetParentIndexNumber(v)
	return _u
}

// SetNillableParentIndexNumber sets the "parent_index_number" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableParentIndexNumber(v *int32) *MediaItemUpdateOne {
	if v != nil {
		_u.SetParentIndexNumber(*v)
	}
	return _u
}

// AddParentIndexNumber adds value to the "parent_index_number" field.
func (_u *MediaItemUpdateOne) AddParentIndexNumber(v int32) *MediaItemUpdateOne {
	_u.mutation.AddParentIndexNumber(v)
	return _u
}

// ClearParentIndexNumber clears the value of the "parent_index_number" field.
func (_u *MediaItemUpdateOne) ClearParentIndexNumber() *MediaItemUpdateOne {
	_u.mutation.ClearParentIndexNumber()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *MediaItemUpdateOne) SetOverview(v string) *MediaItemUpdateOne {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableOverview(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// SetAlbumArtist sets the "album_artist" field.
func (_u *MediaItemUpdateOne) SetAlbumArtist(v string) *MediaItemUpdateOne {
	_u.mutation.SetAlbumArtist(v)
	return _u
}

// SetNillableAlbumArtist sets the "album_artist" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableAlbumArtist(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetAlbumArtist(*v)
	}
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *MediaItemUpdateOne) SetImagePath(v string) *MediaItemUpdateOne {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableImagePath(v *string) *MediaItemUpdateOne {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// SetLibraryID sets the "library" edge to the Library entity by ID.
func (_u *MediaItemUpdateOne) SetLibraryID(id uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.SetLibraryID(id)
	return _u
}

// SetNillableLibraryID sets the "library" edge to the Library entity by ID if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableLibraryID(id *uuid.UUID) *MediaItemUpdateOne {
	if id != nil {
		_u = _u.SetLibraryID(*id)
	}
	return _u
}

// SetLibrary sets the "library" edge to the Library entity.
func (_u *MediaItemUpdateOne) SetLibrary(v *Library) *MediaItemUpdateOne {
	return _u.SetLibraryID(v.ID)
}

// SetParentID sets the "parent" edge to the MediaItem entity by ID.
func (_u *MediaItemUpdateOne) SetParentID(id uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the MediaItem entity by ID if the given value is not nil.
func (_u *MediaItemUpdateOne) SetNillableParentID(id *uuid.UUID) *MediaItemUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdateOne) SetParent(v *MediaItem) *MediaItemUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the MediaItem entity by IDs.
func (_u *MediaItemUpdateOne) AddChildIDs(ids ...uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the MediaItem entity.
func (_u *MediaItemUpdateOne) AddChildren(v ...*MediaItem) *MediaItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the MediaItemMutation object of the builder.
func (_u *MediaItemUpdateOne) Mutation() *MediaItemMutation {
	return _u.mutation
}

// ClearLibrary clears the "library" edge to the Library entity.
func (_u *MediaItemUpdateOne) ClearLibrary() *MediaItemUpdateOne {
	_u.mutation.ClearLibrary()
	return _u
}

// ClearParent clears the "parent" edge to the MediaItem entity.
func (_u *MediaItemUpdateOne) ClearParent() *MediaItemUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the MediaItem entity.
func (_u *MediaItemUpdateOne) ClearChildren() *MediaItemUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to MediaItem entities by IDs.
func (_u *MediaItemUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *MediaItemUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to MediaItem entities.
func (_u *MediaItemUpdateOne) RemoveChildren(v ...*MediaItem) *MediaItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the MediaItemUpdate builder.
func (_u *MediaItemUpdateOne) Where(ps ...predicate.MediaItem) *MediaItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaItemUpdateOne) Select(field string, fields ...string) *MediaItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaItem entity.
func (_u *MediaItemUpdateOne) Save(ctx context.Context) (*MediaItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaItemUpdateOne) SaveX(ctx context.Context) *MediaItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaItemUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := mediaitem.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaItem.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mediaitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MediaItem.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaItemUpdateOne) sqlSave(ctx context.Context) (_node *MediaItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaitem.Table, mediaitem.Columns, sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaitem.FieldID)
		for _, f := range fields {
			if !mediaitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(mediaitem.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mediaitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(mediaitem.FieldSortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(mediaitem.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Container(); ok {
		_spec.SetField(mediaitem.FieldContainer, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunTimeTicks(); ok {
		_spec.SetField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRunTimeTicks(); ok {
		_spec.AddField(mediaitem.FieldRunTimeTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductionYear(); ok {
		_spec.SetField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedProductionYear(); ok {
		_spec.AddField(mediaitem.FieldProductionYear, field.TypeInt32, value)
	}
	if _u.mutation.ProductionYearCleared() {
		_spec.ClearField(mediaitem.FieldProductionYear, field.TypeInt32)
	}
	if value, ok := _u.mutation.IndexNumber(); ok {
		_spec.SetField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.IndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.ParentIndexNumber(); ok {
		_spec.SetField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedParentIndexNumber(); ok {
		_spec.AddField(mediaitem.FieldParentIndexNumber, field.TypeInt32, value)
	}
	if _u.mutation.ParentIndexNumberCleared() {
		_spec.ClearField(mediaitem.FieldParentIndexNumber, field.TypeInt32)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(mediaitem.FieldOverview, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlbumArtist(); ok {
		_spec.SetField(mediaitem.FieldAlbumArtist, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(mediaitem.FieldImagePath, field.TypeString, value)
	}
	if _u.mutation.LibraryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibraryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.LibraryTable,
			Columns: []string{mediaitem.LibraryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaitem.ParentTable,
			Columns: []string{mediaitem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediaitem.ChildrenTable,
			Columns: []string{mediaitem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
