// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/library"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/ent/playstate"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/google/uuid"
)

// MediaItemQuery is the builder for querying MediaItem entities.
type MediaItemQuery struct {
	config
	ctx            *QueryContext
	order          []mediaitem.OrderOption
	inters         []Interceptor
	predicates     []predicate.MediaItem
	withLibrary    *LibraryQuery
	withParent     *MediaItemQuery
	withChildren   *MediaItemQuery
	withPlaystates *PlayStateQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MediaItemQuery builder.
func (_q *MediaItemQuery) Where(ps ...predicate.MediaItem) *MediaItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MediaItemQuery) Limit(limit int) *MediaItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MediaItemQuery) Offset(offset int) *MediaItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MediaItemQuery) Unique(unique bool) *MediaItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MediaItemQuery) Order(o ...mediaitem.OrderOption) *MediaItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLibrary chains the current query on the "library" edge.
func (_q *MediaItemQuery) QueryLibrary() *LibraryQuery {
	query := (&LibraryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaitem.Table, mediaitem.FieldID, selector),
			sqlgraph.To(library.Table, library.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediaitem.LibraryTable, mediaitem.LibraryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (_q *MediaItemQuery) QueryParent() *MediaItemQuery {
	query := (&MediaItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaitem.Table, mediaitem.FieldID, selector),
			sqlgraph.To(mediaitem.Table, mediaitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mediaitem.ParentTable, mediaitem.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (_q *MediaItemQuery) QueryChildren() *MediaItemQuery {
	query := (&MediaItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaitem.Table, mediaitem.FieldID, selector),
			sqlgraph.To(mediaitem.Table, mediaitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, mediaitem.ChildrenTable, mediaitem.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlaystates chains the current query on the "playstates" edge.
func (_q *MediaItemQuery) QueryPlaystates() *PlayStateQuery {
	query := (&PlayStateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mediaitem.Table, mediaitem.FieldID, selector),
			sqlgraph.To(playstate.Table, playstate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, mediaitem.PlaystatesTable, mediaitem.PlaystatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MediaItem entity from the query.
// Returns a *NotFoundError when no MediaItem was found.
func (_q *MediaItemQuery) First(ctx context.Context) (*MediaItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mediaitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MediaItemQuery) FirstX(ctx context.Context) *MediaItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MediaItem ID from the query.
// Returns a *NotFoundError when no MediaItem ID was found.
func (_q *MediaItemQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mediaitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MediaItemQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MediaItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MediaItem entity is found.
// Returns a *NotFoundError when no MediaItem entities are found.
func (_q *MediaItemQuery) Only(ctx context.Context) (*MediaItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mediaitem.Label}
	default:
		return nil, &NotSingularError{mediaitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MediaItemQuery) OnlyX(ctx context.Context) *MediaItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MediaItem ID in the query.
// Returns a *NotSingularError when more than one MediaItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MediaItemQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mediaitem.Label}
	default:
		err = &NotSingularError{mediaitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MediaItemQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MediaItems.
func (_q *MediaItemQuery) All(ctx context.Context) ([]*MediaItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MediaItem, *MediaItemQuery]()
	return withInterceptors[[]*MediaItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MediaItemQuery) AllX(ctx context.Context) []*MediaItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MediaItem IDs.
func (_q *MediaItemQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(mediaitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MediaItemQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MediaItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MediaItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MediaItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MediaItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MediaItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MediaItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MediaItemQuery) Clone() *MediaItemQuery {
	if _q == nil {
		return nil
	}
	return &MediaItemQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]mediaitem.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.MediaItem{}, _q.predicates...),
		withLibrary:    _q.withLibrary.Clone(),
		withParent:     _q.withParent.Clone(),
		withChildren:   _q.withChildren.Clone(),
		withPlaystates: _q.withPlaystates.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLibrary tells the query-builder to eager-load the nodes that are connected to
// the "library" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MediaItemQuery) WithLibrary(opts ...func(*LibraryQuery)) *MediaItemQuery {
	query := (&LibraryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLibrary = query
	return _q
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MediaItemQuery) WithParent(opts ...func(*MediaItemQuery)) *MediaItemQuery {
	query := (&MediaItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MediaItemQuery) WithChildren(opts ...func(*MediaItemQuery)) *MediaItemQuery {
	query := (&MediaItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildren = query
	return _q
}

// WithPlaystates tells the query-builder to eager-load the nodes that are connected to
// the "playstates" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MediaItemQuery) WithPlaystates(opts ...func(*PlayStateQuery)) *MediaItemQuery {
	query := (&PlayStateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlaystates = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Kind mediaitem.Kind `json:"kind,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MediaItem.Query().
//		GroupBy(mediaitem.FieldKind).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MediaItemQuery) GroupBy(field string, fields ...string) *MediaItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MediaItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = mediaitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Kind mediaitem.Kind `json:"kind,omitempty"`
//	}
//
//	client.MediaItem.Query().
//		Select(mediaitem.FieldKind).
//		Scan(ctx, &v)
func (_q *MediaItemQuery) Select(fields ...string) *MediaItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MediaItemSelect{MediaItemQuery: _q}
	sbuild.label = mediaitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MediaItemSelect configured with the given aggregations.
func (_q *MediaItemQuery) Aggregate(fns ...AggregateFunc) *MediaItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MediaItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !mediaitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MediaItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MediaItem, error) {
	var (
		nodes       = []*MediaItem{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withLibrary != nil,
			_q.withParent != nil,
			_q.withChildren != nil,
			_q.withPlaystates != nil,
		}
	)
	if _q.withLibrary != nil || _q.withParent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, mediaitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MediaItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MediaItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLibrary; query != nil {
		if err := _q.loadLibrary(ctx, query, nodes, nil,
			func(n *MediaItem, e *Library) { n.Edges.Library = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *MediaItem, e *MediaItem) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChildren; query != nil {
		if err := _q.loadChildren(ctx, query, nodes,
			func(n *MediaItem) { n.Edges.Children = []*MediaItem{} },
			func(n *MediaItem, e *MediaItem) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPlaystates; query != nil {
		if err := _q.loadPlaystates(ctx, query, nodes,
			func(n *MediaItem) { n.Edges.Playstates = []*PlayState{} },
			func(n *MediaItem, e *PlayState) { n.Edges.Playstates = append(n.Edges.Playstates, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MediaItemQuery) loadLibrary(ctx context.Context, query *LibraryQuery, nodes []*MediaItem, init func(*MediaItem), assign func(*MediaItem, *Library)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MediaItem)
	for i := range nodes {
		if nodes[i].library_items == nil {
			continue
		}
		fk := *nodes[i].library_items
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(library.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "library_items" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MediaItemQuery) loadParent(ctx context.Context, query *MediaItemQuery, nodes []*MediaItem, init func(*MediaItem), assign func(*MediaItem, *MediaItem)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MediaItem)
	for i := range nodes {
		if nodes[i].media_item_children == nil {
			continue
		}
		fk := *nodes[i].media_item_children
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(mediaitem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "media_item_children" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MediaItemQuery) loadChildren(ctx context.Context, query *MediaItemQuery, nodes []*MediaItem, init func(*MediaItem), assign func(*MediaItem, *MediaItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*MediaItem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.MediaItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(mediaitem.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.media_item_children
		if fk == nil {
			return fmt.Errorf(`foreign-key "media_item_children" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "media_item_children" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MediaItemQuery) loadPlaystates(ctx context.Context, query *PlayStateQuery, nodes []*MediaItem, init func(*MediaItem), assign func(*MediaItem, *PlayState)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*MediaItem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PlayState(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(mediaitem.PlaystatesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.media_item_playstates
		if fk == nil {
			return fmt.Errorf(`foreign-key "media_item_playstates" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "media_item_playstates" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MediaItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MediaItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mediaitem.Table, mediaitem.Columns, sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaitem.FieldID)
		for i := range fields {
			if fields[i] != mediaitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MediaItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(mediaitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = mediaitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MediaItemGroupBy is the group-by builder for MediaItem entities.
type MediaItemGroupBy struct {
	selector
	build *MediaItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MediaItemGroupBy) Aggregate(fns ...AggregateFunc) *MediaItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MediaItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaItemQuery, *MediaItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MediaItemGroupBy) sqlScan(ctx context.Context, root *MediaItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MediaItemSelect is the builder for selecting fields of MediaItem entities.
type MediaItemSelect struct {
	*MediaItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MediaItemSelect) Aggregate(fns ...AggregateFunc) *MediaItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MediaItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaItemQuery, *MediaItemSelect](ctx, _s.MediaItemQuery, _s, _s.inters, v)
}

func (_s *MediaItemSelect) sqlScan(ctx context.Context, root *MediaItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
