// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/metadatacache"
	"github.com/google/uuid"
)

// MetadataCacheCreate is the builder for creating a MetadataCache entity.
type MetadataCacheCreate struct {
	config
	mutation *MetadataCacheMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *MetadataCacheCreate) SetProvider(v string) *MetadataCacheCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *MetadataCacheCreate) SetKind(v string) *MetadataCacheCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *MetadataCacheCreate) SetKey(v string) *MetadataCacheCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *MetadataCacheCreate) SetPayload(v []byte) *MetadataCacheCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNotFound sets the "not_found" field.
func (_c *MetadataCacheCreate) SetNotFound(v bool) *MetadataCacheCreate {
	_c.mutation.SetNotFound(v)
	return _c
}

// SetNillableNotFound sets the "not_found" field if the given value is not nil.
func (_c *MetadataCacheCreate) SetNillableNotFound(v *bool) *MetadataCacheCreate {
	if v != nil {
		_c.SetNotFound(*v)
	}
	return _c
}

// SetFetchedAt sets the "fetched_at" field.
func (_c *MetadataCacheCreate) SetFetchedAt(v time.Time) *MetadataCacheCreate {
	_c.mutation.SetFetchedAt(v)
	return _c
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_c *MetadataCacheCreate) SetNillableFetchedAt(v *time.Time) *MetadataCacheCreate {
	if v != nil {
		_c.SetFetchedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MetadataCacheCreate) SetID(v uuid.UUID) *MetadataCacheCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MetadataCacheCreate) SetNillableID(v *uuid.UUID) *MetadataCacheCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MetadataCacheMutation object of the builder.
func (_c *MetadataCacheCreate) Mutation() *MetadataCacheMutation {
	return _c.mutation
}

// Save creates the MetadataCache in the database.
func (_c *MetadataCacheCreate) Save(ctx context.Context) (*MetadataCache, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MetadataCacheCreate) SaveX(ctx context.Context) *MetadataCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetadataCacheCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetadataCacheCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MetadataCacheCreate) defaults() {
	if _, ok := _c.mutation.NotFound(); !ok {
		v := metadatacache.DefaultNotFound
		_c.mutation.SetNotFound(v)
	}
	if _, ok := _c.mutation.FetchedAt(); !ok {
		v := metadatacache.DefaultFetchedAt()
		_c.mutation.SetFetchedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := metadatacache.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MetadataCacheCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "MetadataCache.provider"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "MetadataCache.kind"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "MetadataCache.key"`)}
	}
	if _, ok := _c.mutation.NotFound(); !ok {
		return &ValidationError{Name: "not_found", err: errors.New(`ent: missing required field "MetadataCache.not_found"`)}
	}
	if _, ok := _c.mutation.FetchedAt(); !ok {
		return &ValidationError{Name: "fetched_at", err: errors.New(`ent: missing required field "MetadataCache.fetched_at"`)}
	}
	return nil
}

func (_c *MetadataCacheCreate) sqlSave(ctx context.Context) (*MetadataCache, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MetadataCacheCreate) createSpec() (*MetadataCache, *sqlgraph.CreateSpec) {
	var (
		_node = &MetadataCache{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(metadatacache.Table, sqlgraph.NewFieldSpec(metadatacache.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(metadatacache.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(metadatacache.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(metadatacache.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(metadatacache.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.NotFound(); ok {
		_spec.SetField(metadatacache.FieldNotFound, field.TypeBool, value)
		_node.NotFound = value
	}
	if value, ok := _c.mutation.FetchedAt(); ok {
		_spec.SetField(metadatacache.FieldFetchedAt, field.TypeTime, value)
		_node.FetchedAt = value
	}
	return _node, _spec
}

// MetadataCacheCreateBulk is the builder for creating many MetadataCache entities in bulk.
type MetadataCacheCreateBulk struct {
	config
	err      error
	builders []*MetadataCacheCreate
}

// Save creates the MetadataCache entities in the database.
func (_c *MetadataCacheCreateBulk) Save(ctx context.Context) ([]*MetadataCache, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MetadataCache, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MetadataCacheMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MetadataCacheCreateBulk) SaveX(ctx context.Context) []*MetadataCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetadataCacheCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetadataCacheCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
