// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gartnera/gofin/ent/metadatacache"
	"github.com/google/uuid"
)

// MetadataCache is the model entity for the MetadataCache schema.
type MetadataCache struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"payload,omitempty"`
	// NotFound holds the value of the "not_found" field.
	NotFound bool `json:"not_found,omitempty"`
	// FetchedAt holds the value of the "fetched_at" field.
	FetchedAt    time.Time `json:"fetched_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MetadataCache) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case metadatacache.FieldPayload:
			values[i] = new([]byte)
		case metadatacache.FieldNotFound:
			values[i] = new(sql.NullBool)
		case metadatacache.FieldProvider, metadatacache.FieldKind, metadatacache.FieldKey:
			values[i] = new(sql.NullString)
		case metadatacache.FieldFetchedAt:
			values[i] = new(sql.NullTime)
		case metadatacache.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MetadataCache fields.
func (_m *MetadataCache) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case metadatacache.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case metadatacache.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case metadatacache.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case metadatacache.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case metadatacache.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				_m.Payload = *value
			}
		case metadatacache.FieldNotFound:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field not_found", values[i])
			} else if value.Valid {
				_m.NotFound = value.Bool
			}
		case metadatacache.FieldFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fetched_at", values[i])
			} else if value.Valid {
				_m.FetchedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MetadataCache.
// This includes values selected through modifiers, order, etc.
func (_m *MetadataCache) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MetadataCache.
// Note that you need to call MetadataCache.Unwrap() before calling this method if this MetadataCache
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MetadataCache) Update() *MetadataCacheUpdateOne {
	return NewMetadataCacheClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MetadataCache entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MetadataCache) Unwrap() *MetadataCache {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MetadataCache is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MetadataCache) String() string {
	var builder strings.Builder
	builder.WriteString("MetadataCache(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("not_found=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotFound))
	builder.WriteString(", ")
	builder.WriteString("fetched_at=")
	builder.WriteString(_m.FetchedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MetadataCaches is a parsable slice of MetadataCache.
type MetadataCaches []*MetadataCache
