// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/metadatacache"
	"github.com/gartnera/gofin/ent/predicate"
)

// MetadataCacheUpdate is the builder for updating MetadataCache entities.
type MetadataCacheUpdate struct {
	config
	hooks    []Hook
	mutation *MetadataCacheMutation
}

// Where appends a list predicates to the MetadataCacheUpdate builder.
func (_u *MetadataCacheUpdate) Where(ps ...predicate.MetadataCache) *MetadataCacheUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *MetadataCacheUpdate) SetProvider(v string) *MetadataCacheUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *MetadataCacheUpdate) SetNillableProvider(v *string) *MetadataCacheUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *MetadataCacheUpdate) SetKind(v string) *MetadataCacheUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MetadataCacheUpdate) SetNillableKind(v *string) *MetadataCacheUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *MetadataCacheUpdate) SetKey(v string) *MetadataCacheUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *MetadataCacheUpdate) SetNillableKey(v *string) *MetadataCacheUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MetadataCacheUpdate) SetPayload(v []byte) *MetadataCacheUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MetadataCacheUpdate) ClearPayload() *MetadataCacheUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetNotFound sets the "not_found" field.
func (_u *MetadataCacheUpdate) SetNotFound(v bool) *MetadataCacheUpdate {
	_u.mutation.SetNotFound(v)
	return _u
}

// SetNillableNotFound sets the "not_found" field if the given value is not nil.
func (_u *MetadataCacheUpdate) SetNillableNotFound(v *bool) *MetadataCacheUpdate {
	if v != nil {
		_u.SetNotFound(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *MetadataCacheUpdate) SetFetchedAt(v time.Time) *MetadataCacheUpdate {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *MetadataCacheUpdate) SetNillableFetchedAt(v *time.Time) *MetadataCacheUpdate {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// Mutation returns the MetadataCacheMutation object of the builder.
func (_u *MetadataCacheUpdate) Mutation() *MetadataCacheMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MetadataCacheUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetadataCacheUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MetadataCacheUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetadataCacheUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MetadataCacheUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(metadatacache.Table, metadatacache.Columns, sqlgraph.NewFieldSpec(metadatacache.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(metadatacache.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(metadatacache.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(metadatacache.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(metadatacache.FieldPayload, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(metadatacache.FieldPayload, field.TypeBytes)
	}
	if value, ok := _u.mutation.NotFound(); ok {
		_spec.SetField(metadatacache.FieldNotFound, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(metadatacache.FieldFetchedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metadatacache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MetadataCacheUpdateOne is the builder for updating a single MetadataCache entity.
type MetadataCacheUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetadataCacheMutation
}

// SetProvider sets the "provider" field.
func (_u *MetadataCacheUpdateOne) SetProvider(v string) *MetadataCacheUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *MetadataCacheUpdateOne) SetNillableProvider(v *string) *MetadataCacheUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *MetadataCacheUpdateOne) SetKind(v string) *MetadataCacheUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MetadataCacheUpdateOne) SetNillableKind(v *string) *MetadataCacheUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *MetadataCacheUpdateOne) SetKey(v string) *MetadataCacheUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *MetadataCacheUpdateOne) SetNillableKey(v *string) *MetadataCacheUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MetadataCacheUpdateOne) SetPayload(v []byte) *MetadataCacheUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MetadataCacheUpdateOne) ClearPayload() *MetadataCacheUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetNotFound sets the "not_found" field.
func (_u *MetadataCacheUpdateOne) SetNotFound(v bool) *MetadataCacheUpdateOne {
	_u.mutation.SetNotFound(v)
	return _u
}

// SetNillableNotFound sets the "not_found" field if the given value is not nil.
func (_u *MetadataCacheUpdateOne) SetNillableNotFound(v *bool) *MetadataCacheUpdateOne {
	if v != nil {
		_u.SetNotFound(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *MetadataCacheUpdateOne) SetFetchedAt(v time.Time) *MetadataCacheUpdateOne {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *MetadataCacheUpdateOne) SetNillableFetchedAt(v *time.Time) *MetadataCacheUpdateOne {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// Mutation returns the MetadataCacheMutation object of the builder.
func (_u *MetadataCacheUpdateOne) Mutation() *MetadataCacheMutation {
	return _u.mutation
}

// Where appends a list predicates to the MetadataCacheUpdate builder.
func (_u *MetadataCacheUpdateOne) Where(ps ...predicate.MetadataCache) *MetadataCacheUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MetadataCacheUpdateOne) Select(field string, fields ...string) *MetadataCacheUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MetadataCache entity.
func (_u *MetadataCacheUpdateOne) Save(ctx context.Context) (*MetadataCache, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetadataCacheUpdateOne) SaveX(ctx context.Context) *MetadataCache {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MetadataCacheUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetadataCacheUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MetadataCacheUpdateOne) sqlSave(ctx context.Context) (_node *MetadataCache, err error) {
	_spec := sqlgraph.NewUpdateSpec(metadatacache.Table, metadatacache.Columns, sqlgraph.NewFieldSpec(metadatacache.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MetadataCache.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, metadatacache.FieldID)
		for _, f := range fields {
			if !metadatacache.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != metadatacache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(metadatacache.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(metadatacache.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(metadatacache.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(metadatacache.FieldPayload, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(metadatacache.FieldPayload, field.TypeBytes)
	}
	if value, ok := _u.mutation.NotFound(); ok {
		_spec.SetField(metadatacache.FieldNotFound, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(metadatacache.FieldFetchedAt, field.TypeTime, value)
	}
	_node = &MetadataCache{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metadatacache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
