// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/ent/playstate"
	"github.com/gartnera/gofin/ent/user"
	"github.com/google/uuid"
)

// PlayState is the model entity for the PlayState schema.
type PlayState struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Played holds the value of the "played" field.
	Played bool `json:"played,omitempty"`
	// PlaybackPositionTicks holds the value of the "playback_position_ticks" field.
	PlaybackPositionTicks int64 `json:"playback_position_ticks,omitempty"`
	// PlayCount holds the value of the "play_count" field.
	PlayCount int `json:"play_count,omitempty"`
	// LastPlayedDate holds the value of the "last_played_date" field.
	LastPlayedDate *time.Time `json:"last_played_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlayStateQuery when eager-loading is set.
	Edges                 PlayStateEdges `json:"edges"`
	media_item_playstates *uuid.UUID
	user_playstates       *uuid.UUID
	selectValues          sql.SelectValues
}

// PlayStateEdges holds the relations/edges for other nodes in the graph.
type PlayStateEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Item holds the value of the item edge.
	Item *MediaItem `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayStateEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayStateEdges) ItemOrErr() (*MediaItem, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: mediaitem.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playstate.FieldPlayed:
			values[i] = new(sql.NullBool)
		case playstate.FieldPlaybackPositionTicks, playstate.FieldPlayCount:
			values[i] = new(sql.NullInt64)
		case playstate.FieldLastPlayedDate:
			values[i] = new(sql.NullTime)
		case playstate.FieldID:
			values[i] = new(uuid.UUID)
		case playstate.ForeignKeys[0]: // media_item_playstates
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case playstate.ForeignKeys[1]: // user_playstates
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayState fields.
func (_m *PlayState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playstate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case playstate.FieldPlayed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field played", values[i])
			} else if value.Valid {
				_m.Played = value.Bool
			}
		case playstate.FieldPlaybackPositionTicks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field playback_position_ticks", values[i])
			} else if value.Valid {
				_m.PlaybackPositionTicks = value.Int64
			}
		case playstate.FieldPlayCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field play_count", values[i])
			} else if value.Valid {
				_m.PlayCount = int(value.Int64)
			}
		case playstate.FieldLastPlayedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_played_date", values[i])
			} else if value.Valid {
				_m.LastPlayedDate = new(time.Time)
				*_m.LastPlayedDate = value.Time
			}
		case playstate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field media_item_playstates", values[i])
			} else if value.Valid {
				_m.media_item_playstates = new(uuid.UUID)
				*_m.media_item_playstates = *value.S.(*uuid.UUID)
			}
		case playstate.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_playstates", values[i])
			} else if value.Valid {
				_m.user_playstates = new(uuid.UUID)
				*_m.user_playstates = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayState.
// This includes values selected through modifiers, order, etc.
func (_m *PlayState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PlayState entity.
func (_m *PlayState) QueryUser() *UserQuery {
	return NewPlayStateClient(_m.config).QueryUser(_m)
}

// QueryItem queries the "item" edge of the PlayState entity.
func (_m *PlayState) QueryItem() *MediaItemQuery {
	return NewPlayStateClient(_m.config).QueryItem(_m)
}

// Update returns a builder for updating this PlayState.
// Note that you need to call PlayState.Unwrap() before calling this method if this PlayState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlayState) Update() *PlayStateUpdateOne {
	return NewPlayStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlayState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlayState) Unwrap() *PlayState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlayState) String() string {
	var builder strings.Builder
	builder.WriteString("PlayState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("played=")
	builder.WriteString(fmt.Sprintf("%v", _m.Played))
	builder.WriteString(", ")
	builder.WriteString("playback_position_ticks=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlaybackPositionTicks))
	builder.WriteString(", ")
	builder.WriteString("play_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlayCount))
	builder.WriteString(", ")
	if v := _m.LastPlayedDate; v != nil {
		builder.WriteString("last_played_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PlayStates is a parsable slice of PlayState.
type PlayStates []*PlayState
