// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/ent/playstate"
	"github.com/gartnera/gofin/ent/user"
	"github.com/google/uuid"
)

// PlayStateCreate is the builder for creating a PlayState entity.
type PlayStateCreate struct {
	config
	mutation *PlayStateMutation
	hooks    []Hook
}

// SetPlayed sets the "played" field.
func (_c *PlayStateCreate) SetPlayed(v bool) *PlayStateCreate {
	_c.mutation.SetPlayed(v)
	return _c
}

// SetNillablePlayed sets the "played" field if the given value is not nil.
func (_c *PlayStateCreate) SetNillablePlayed(v *bool) *PlayStateCreate {
	if v != nil {
		_c.SetPlayed(*v)
	}
	return _c
}

// SetPlaybackPositionTicks sets the "playback_position_ticks" field.
func (_c *PlayStateCreate) SetPlaybackPositionTicks(v int64) *PlayStateCreate {
	_c.mutation.SetPlaybackPositionTicks(v)
	return _c
}

// SetNillablePlaybackPositionTicks sets the "playback_position_ticks" field if the given value is not nil.
func (_c *PlayStateCreate) SetNillablePlaybackPositionTicks(v *int64) *PlayStateCreate {
	if v != nil {
		_c.SetPlaybackPositionTicks(*v)
	}
	return _c
}

// SetPlayCount sets the "play_count" field.
func (_c *PlayStateCreate) SetPlayCount(v int) *PlayStateCreate {
	_c.mutation.SetPlayCount(v)
	return _c
}

// SetNillablePlayCount sets the "play_count" field if the given value is not nil.
func (_c *PlayStateCreate) SetNillablePlayCount(v *int) *PlayStateCreate {
	if v != nil {
		_c.SetPlayCount(*v)
	}
	return _c
}

// SetLastPlayedDate sets the "last_played_date" field.
func (_c *PlayStateCreate) SetLastPlayedDate(v time.Time) *PlayStateCreate {
	_c.mutation.SetLastPlayedDate(v)
	return _c
}

// SetNillableLastPlayedDate sets the "last_played_date" field if the given value is not nil.
func (_c *PlayStateCreate) SetNillableLastPlayedDate(v *time.Time) *PlayStateCreate {
	if v != nil {
		_c.SetLastPlayedDate(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlayStateCreate) SetID(v uuid.UUID) *PlayStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlayStateCreate) SetNillableID(v *uuid.UUID) *PlayStateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *PlayStateCreate) SetUserID(id uuid.UUID) *PlayStateCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PlayStateCreate) SetUser(v *User) *PlayStateCreate {
	return _c.SetUserID(v.ID)
}

// SetItemID sets the "item" edge to the MediaItem entity by ID.
func (_c *PlayStateCreate) SetItemID(id uuid.UUID) *PlayStateCreate {
	_c.mutation.SetItemID(id)
	return _c
}

// SetItem sets the "item" edge to the MediaItem entity.
func (_c *PlayStateCreate) SetItem(v *MediaItem) *PlayStateCreate {
	return _c.SetItemID(v.ID)
}

// Mutation returns the PlayStateMutation object of the builder.
func (_c *PlayStateCreate) Mutation() *PlayStateMutation {
	return _c.mutation
}

// Save creates the PlayState in the database.
func (_c *PlayStateCreate) Save(ctx context.Context) (*PlayState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayStateCreate) SaveX(ctx context.Context) *PlayState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayStateCreate) defaults() {
	if _, ok := _c.mutation.Played(); !ok {
		v := playstate.DefaultPlayed
		_c.mutation.SetPlayed(v)
	}
	if _, ok := _c.mutation.PlaybackPositionTicks(); !ok {
		v := playstate.DefaultPlaybackPositionTicks
		_c.mutation.SetPlaybackPositionTicks(v)
	}
	if _, ok := _c.mutation.PlayCount(); !ok {
		v := playstate.DefaultPlayCount
		_c.mutation.SetPlayCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := playstate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayStateCreate) check() error {
	if _, ok := _c.mutation.Played(); !ok {
		return &ValidationError{Name: "played", err: errors.New(`ent: missing required field "PlayState.played"`)}
	}
	if _, ok := _c.mutation.PlaybackPositionTicks(); !ok {
		return &ValidationError{Name: "playback_position_ticks", err: errors.New(`ent: missing required field "PlayState.playback_position_ticks"`)}
	}
	if _, ok := _c.mutation.PlayCount(); !ok {
		return &ValidationError{Name: "play_count", err: errors.New(`ent: missing required field "PlayState.play_count"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PlayState.user"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "PlayState.item"`)}
	}
	return nil
}

func (_c *PlayStateCreate) sqlSave(ctx context.Context) (*PlayState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayStateCreate) createSpec() (*PlayState, *sqlgraph.CreateSpec) {
	var (
		_node = &PlayState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playstate.Table, sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Played(); ok {
		_spec.SetField(playstate.FieldPlayed, field.TypeBool, value)
		_node.Played = value
	}
	if value, ok := _c.mutation.PlaybackPositionTicks(); ok {
		_spec.SetField(playstate.FieldPlaybackPositionTicks, field.TypeInt64, value)
		_node.PlaybackPositionTicks = value
	}
	if value, ok := _c.mutation.PlayCount(); ok {
		_spec.SetField(playstate.FieldPlayCount, field.TypeInt, value)
		_node.PlayCount = value
	}
	if value, ok := _c.mutation.LastPlayedDate(); ok {
		_spec.SetField(playstate.FieldLastPlayedDate, field.TypeTime, value)
		_node.LastPlayedDate = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.UserTable,
			Columns: []string{playstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_playstates = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.ItemTable,
			Columns: []string{playstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.media_item_playstates = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlayStateCreateBulk is the builder for creating many PlayState entities in bulk.
type PlayStateCreateBulk struct {
	config
	err      error
	builders []*PlayStateCreate
}

// Save creates the PlayState entities in the database.
func (_c *PlayStateCreateBulk) Save(ctx context.Context) ([]*PlayState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlayState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayStateCreateBulk) SaveX(ctx context.Context) []*PlayState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
