// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/ent/playstate"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/gartnera/gofin/ent/user"
	"github.com/google/uuid"
)

// PlayStateUpdate is the builder for updating PlayState entities.
type PlayStateUpdate struct {
	config
	hooks    []Hook
	mutation *PlayStateMutation
}

// Where appends a list predicates to the PlayStateUpdate builder.
func (_u *PlayStateUpdate) Where(ps ...predicate.PlayState) *PlayStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlayed sets the "played" field.
func (_u *PlayStateUpdate) SetPlayed(v bool) *PlayStateUpdate {
	_u.mutation.SetPlayed(v)
	return _u
}

// SetNillablePlayed sets the "played" field if the given value is not nil.
func (_u *PlayStateUpdate) SetNillablePlayed(v *bool) *PlayStateUpdate {
	if v != nil {
		_u.SetPlayed(*v)
	}
	return _u
}

// SetPlaybackPositionTicks sets the "playback_position_ticks" field.
func (_u *PlayStateUpdate) SetPlaybackPositionTicks(v int64) *PlayStateUpdate {
	_u.mutation.ResetPlaybackPositionTicks()
	_u.mutation.SetPlaybackPositionTicks(v)
	return _u
}

// SetNillablePlaybackPositionTicks sets the "playback_position_ticks" field if the given value is not nil.
func (_u *PlayStateUpdate) SetNillablePlaybackPositionTicks(v *int64) *PlayStateUpdate {
	if v != nil {
		_u.SetPlaybackPositionTicks(*v)
	}
	return _u
}

// AddPlaybackPositionTicks adds value to the "playback_position_ticks" field.
func (_u *PlayStateUpdate) AddPlaybackPositionTicks(v int64) *PlayStateUpdate {
	_u.mutation.AddPlaybackPositionTicks(v)
	return _u
}

// SetPlayCount sets the "play_count" field.
func (_u *PlayStateUpdate) SetPlayCount(v int) *PlayStateUpdate {
	_u.mutation.ResetPlayCount()
	_u.mutation.SetPlayCount(v)
	return _u
}

// SetNillablePlayCount sets the "play_count" field if the given value is not nil.
func (_u *PlayStateUpdate) SetNillablePlayCount(v *int) *PlayStateUpdate {
	if v != nil {
		_u.SetPlayCount(*v)
	}
	return _u
}

// AddPlayCount adds value to the "play_count" field.
func (_u *PlayStateUpdate) AddPlayCount(v int) *PlayStateUpdate {
	_u.mutation.AddPlayCount(v)
	return _u
}

// SetLastPlayedDate sets the "last_played_date" field.
func (_u *PlayStateUpdate) SetLastPlayedDate(v time.Time) *PlayStateUpdate {
	_u.mutation.SetLastPlayedDate(v)
	return _u
}

// SetNillableLastPlayedDate sets the "last_played_date" field if the given value is not nil.
func (_u *PlayStateUpdate) SetNillableLastPlayedDate(v *time.Time) *PlayStateUpdate {
	if v != nil {
		_u.SetLastPlayedDate(*v)
	}
	return _u
}

// ClearLastPlayedDate clears the value of the "last_played_date" field.
func (_u *PlayStateUpdate) ClearLastPlayedDate() *PlayStateUpdate {
	_u.mutation.ClearLastPlayedDate()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PlayStateUpdate) SetUserID(id uuid.UUID) *PlayStateUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PlayStateUpdate) SetUser(v *User) *PlayStateUpdate {
	return _u.SetUserID(v.ID)
}

// SetItemID sets the "item" edge to the MediaItem entity by ID.
func (_u *PlayStateUpdate) SetItemID(id uuid.UUID) *PlayStateUpdate {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the MediaItem entity.
func (_u *PlayStateUpdate) SetItem(v *MediaItem) *PlayStateUpdate {
	return _u.SetItemID(v.ID)
}

// Mutation returns the PlayStateMutation object of the builder.
func (_u *PlayStateUpdate) Mutation() *PlayStateMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PlayStateUpdate) ClearUser() *PlayStateUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearItem clears the "item" edge to the MediaItem entity.
func (_u *PlayStateUpdate) ClearItem() *PlayStateUpdate {
	_u.mutation.ClearItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayStateUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayState.user"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayState.item"`)
	}
	return nil
}

func (_u *PlayStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playstate.Table, playstate.Columns, sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Played(); ok {
		_spec.SetField(playstate.FieldPlayed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PlaybackPositionTicks(); ok {
		_spec.SetField(playstate.FieldPlaybackPositionTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlaybackPositionTicks(); ok {
		_spec.AddField(playstate.FieldPlaybackPositionTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlayCount(); ok {
		_spec.SetField(playstate.FieldPlayCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayCount(); ok {
		_spec.AddField(playstate.FieldPlayCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastPlayedDate(); ok {
		_spec.SetField(playstate.FieldLastPlayedDate, field.TypeTime, value)
	}
	if _u.mutation.LastPlayedDateCleared() {
		_spec.ClearField(playstate.FieldLastPlayedDate, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.UserTable,
			Columns: []string{playstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.UserTable,
			Columns: []string{playstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.ItemTable,
			Columns: []string{playstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.ItemTable,
			Columns: []string{playstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayStateUpdateOne is the builder for updating a single PlayState entity.
type PlayStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayStateMutation
}

// SetPlayed sets the "played" field.
func (_u *PlayStateUpdateOne) SetPlayed(v bool) *PlayStateUpdateOne {
	_u.mutation.SetPlayed(v)
	return _u
}

// SetNillablePlayed sets the "played" field if the given value is not nil.
func (_u *PlayStateUpdateOne) SetNillablePlayed(v *bool) *PlayStateUpdateOne {
	if v != nil {
		_u.SetPlayed(*v)
	}
	return _u
}

// SetPlaybackPositionTicks sets the "playback_position_ticks" field.
func (_u *PlayStateUpdateOne) SetPlaybackPositionTicks(v int64) *PlayStateUpdateOne {
	_u.mutation.ResetPlaybackPositionTicks()
	_u.mutation.SetPlaybackPositionTicks(v)
	return _u
}

// SetNillablePlaybackPositionTicks sets the "playback_position_ticks" field if the given value is not nil.
func (_u *PlayStateUpdateOne) SetNillablePlaybackPositionTicks(v *int64) *PlayStateUpdateOne {
	if v != nil {
		_u.SetPlaybackPositionTicks(*v)
	}
	return _u
}

// AddPlaybackPositionTicks adds value to the "playback_position_ticks" field.
func (_u *PlayStateUpdateOne) AddPlaybackPositionTicks(v int64) *PlayStateUpdateOne {
	_u.mutation.AddPlaybackPositionTicks(v)
	return _u
}

// SetPlayCount sets the "play_count" field.
func (_u *PlayStateUpdateOne) SetPlayCount(v int) *PlayStateUpdateOne {
	_u.mutation.ResetPlayCount()
	_u.mutation.SetPlayCount(v)
	return _u
}

// SetNillablePlayCount sets the "play_count" field if the given value is not nil.
func (_u *PlayStateUpdateOne) SetNillablePlayCount(v *int) *PlayStateUpdateOne {
	if v != nil {
		_u.SetPlayCount(*v)
	}
	return _u
}

// AddPlayCount adds value to the "play_count" field.
func (_u *PlayStateUpdateOne) AddPlayCount(v int) *PlayStateUpdateOne {
	_u.mutation.AddPlayCount(v)
	return _u
}

// SetLastPlayedDate sets the "last_played_date" field.
func (_u *PlayStateUpdateOne) SetLastPlayedDate(v time.Time) *PlayStateUpdateOne {
	_u.mutation.SetLastPlayedDate(v)
	return _u
}

// SetNillableLastPlayedDate sets the "last_played_date" field if the given value is not nil.
func (_u *PlayStateUpdateOne) SetNillableLastPlayedDate(v *time.Time) *PlayStateUpdateOne {
	if v != nil {
		_u.SetLastPlayedDate(*v)
	}
	return _u
}

// ClearLastPlayedDate clears the value of the "last_played_date" field.
func (_u *PlayStateUpdateOne) ClearLastPlayedDate() *PlayStateUpdateOne {
	_u.mutation.ClearLastPlayedDate()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PlayStateUpdateOne) SetUserID(id uuid.UUID) *PlayStateUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PlayStateUpdateOne) SetUser(v *User) *PlayStateUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetItemID sets the "item" edge to the MediaItem entity by ID.
func (_u *PlayStateUpdateOne) SetItemID(id uuid.UUID) *PlayStateUpdateOne {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the MediaItem entity.
func (_u *PlayStateUpdateOne) SetItem(v *MediaItem) *PlayStateUpdateOne {
	return _u.SetItemID(v.ID)
}

// Mutation returns the PlayStateMutation object of the builder.
func (_u *PlayStateUpdateOne) Mutation() *PlayStateMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PlayStateUpdateOne) ClearUser() *PlayStateUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearItem clears the "item" edge to the MediaItem entity.
func (_u *PlayStateUpdateOne) ClearItem() *PlayStateUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// Where appends a list predicates to the PlayStateUpdate builder.
func (_u *PlayStateUpdateOne) Where(ps ...predicate.PlayState) *PlayStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayStateUpdateOne) Select(field string, fields ...string) *PlayStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlayState entity.
func (_u *PlayStateUpdateOne) Save(ctx context.Context) (*PlayState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayStateUpdateOne) SaveX(ctx context.Context) *PlayState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayStateUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayState.user"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayState.item"`)
	}
	return nil
}

func (_u *PlayStateUpdateOne) sqlSave(ctx context.Context) (_node *PlayState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playstate.Table, playstate.Columns, sqlgraph.NewFieldSpec(playstate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlayState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playstate.FieldID)
		for _, f := range fields {
			if !playstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Played(); ok {
		_spec.SetField(playstate.FieldPlayed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PlaybackPositionTicks(); ok {
		_spec.SetField(playstate.FieldPlaybackPositionTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlaybackPositionTicks(); ok {
		_spec.AddField(playstate.FieldPlaybackPositionTicks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlayCount(); ok {
		_spec.SetField(playstate.FieldPlayCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayCount(); ok {
		_spec.AddField(playstate.FieldPlayCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastPlayedDate(); ok {
		_spec.SetField(playstate.FieldLastPlayedDate, field.TypeTime, value)
	}
	if _u.mutation.LastPlayedDateCleared() {
		_spec.ClearField(playstate.FieldLastPlayedDate, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.UserTable,
			Columns: []string{playstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.UserTable,
			Columns: []string{playstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.ItemTable,
			Columns: []string{playstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playstate.ItemTable,
			Columns: []string{playstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlayState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
