// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/gartnera/gofin/ent/accesstoken"
	"github.com/gartnera/gofin/ent/library"
	"github.com/gartnera/gofin/ent/mediaitem"
	"github.com/gartnera/gofin/ent/schema"
	"github.com/gartnera/gofin/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accesstokenFields := schema.AccessToken{}.Fields()
	_ = accesstokenFields
	// accesstokenDescToken is the schema descriptor for token field.
	accesstokenDescToken := accesstokenFields[0].Descriptor()
	// accesstoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	accesstoken.TokenValidator = accesstokenDescToken.Validators[0].(func(string) error)
	// accesstokenDescClient is the schema descriptor for client field.
	accesstokenDescClient := accesstokenFields[1].Descriptor()
	// accesstoken.DefaultClient holds the default value on creation for the client field.
	accesstoken.DefaultClient = accesstokenDescClient.Default.(string)
	// accesstokenDescDevice is the schema descriptor for device field.
	accesstokenDescDevice := accesstokenFields[2].Descriptor()
	// accesstoken.DefaultDevice holds the default value on creation for the device field.
	accesstoken.DefaultDevice = accesstokenDescDevice.Default.(string)
	// accesstokenDescDeviceID is the schema descriptor for device_id field.
	accesstokenDescDeviceID := accesstokenFields[3].Descriptor()
	// accesstoken.DefaultDeviceID holds the default value on creation for the device_id field.
	accesstoken.DefaultDeviceID = accesstokenDescDeviceID.Default.(string)
	// accesstokenDescVersion is the schema descriptor for version field.
	accesstokenDescVersion := accesstokenFields[4].Descriptor()
	// accesstoken.DefaultVersion holds the default value on creation for the version field.
	accesstoken.DefaultVersion = accesstokenDescVersion.Default.(string)
	// accesstokenDescCreatedAt is the schema descriptor for created_at field.
	accesstokenDescCreatedAt := accesstokenFields[5].Descriptor()
	// accesstoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	accesstoken.DefaultCreatedAt = accesstokenDescCreatedAt.Default.(func() time.Time)
	libraryFields := schema.Library{}.Fields()
	_ = libraryFields
	// libraryDescName is the schema descriptor for name field.
	libraryDescName := libraryFields[1].Descriptor()
	// library.NameValidator is a validator for the "name" field. It is called by the builders before save.
	library.NameValidator = libraryDescName.Validators[0].(func(string) error)
	// libraryDescPath is the schema descriptor for path field.
	libraryDescPath := libraryFields[3].Descriptor()
	// library.PathValidator is a validator for the "path" field. It is called by the builders before save.
	library.PathValidator = libraryDescPath.Validators[0].(func(string) error)
	// libraryDescID is the schema descriptor for id field.
	libraryDescID := libraryFields[0].Descriptor()
	// library.DefaultID holds the default value on creation for the id field.
	library.DefaultID = libraryDescID.Default.(func() uuid.UUID)
	mediaitemFields := schema.MediaItem{}.Fields()
	_ = mediaitemFields
	// mediaitemDescName is the schema descriptor for name field.
	mediaitemDescName := mediaitemFields[2].Descriptor()
	// mediaitem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mediaitem.NameValidator = mediaitemDescName.Validators[0].(func(string) error)
	// mediaitemDescSortName is the schema descriptor for sort_name field.
	mediaitemDescSortName := mediaitemFields[3].Descriptor()
	// mediaitem.DefaultSortName holds the default value on creation for the sort_name field.
	mediaitem.DefaultSortName = mediaitemDescSortName.Default.(string)
	// mediaitemDescPath is the schema descriptor for path field.
	mediaitemDescPath := mediaitemFields[4].Descriptor()
	// mediaitem.DefaultPath holds the default value on creation for the path field.
	mediaitem.DefaultPath = mediaitemDescPath.Default.(string)
	// mediaitemDescContainer is the schema descriptor for container field.
	mediaitemDescContainer := mediaitemFields[5].Descriptor()
	// mediaitem.DefaultContainer holds the default value on creation for the container field.
	mediaitem.DefaultContainer = mediaitemDescContainer.Default.(string)
	// mediaitemDescRunTimeTicks is the schema descriptor for run_time_ticks field.
	mediaitemDescRunTimeTicks := mediaitemFields[6].Descriptor()
	// mediaitem.DefaultRunTimeTicks holds the default value on creation for the run_time_ticks field.
	mediaitem.DefaultRunTimeTicks = mediaitemDescRunTimeTicks.Default.(int64)
	// mediaitemDescOverview is the schema descriptor for overview field.
	mediaitemDescOverview := mediaitemFields[10].Descriptor()
	// mediaitem.DefaultOverview holds the default value on creation for the overview field.
	mediaitem.DefaultOverview = mediaitemDescOverview.Default.(string)
	// mediaitemDescAlbumArtist is the schema descriptor for album_artist field.
	mediaitemDescAlbumArtist := mediaitemFields[11].Descriptor()
	// mediaitem.DefaultAlbumArtist holds the default value on creation for the album_artist field.
	mediaitem.DefaultAlbumArtist = mediaitemDescAlbumArtist.Default.(string)
	// mediaitemDescImagePath is the schema descriptor for image_path field.
	mediaitemDescImagePath := mediaitemFields[12].Descriptor()
	// mediaitem.DefaultImagePath holds the default value on creation for the image_path field.
	mediaitem.DefaultImagePath = mediaitemDescImagePath.Default.(string)
	// mediaitemDescID is the schema descriptor for id field.
	mediaitemDescID := mediaitemFields[0].Descriptor()
	// mediaitem.DefaultID holds the default value on creation for the id field.
	mediaitem.DefaultID = mediaitemDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[3].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
