// Code generated by ent, DO NOT EDIT.

package playstate

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the playstate type in the database.
	Label = "play_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlayed holds the string denoting the played field in the database.
	FieldPlayed = "played"
	// FieldPlaybackPositionTicks holds the string denoting the playback_position_ticks field in the database.
	FieldPlaybackPositionTicks = "playback_position_ticks"
	// FieldPlayCount holds the string denoting the play_count field in the database.
	FieldPlayCount = "play_count"
	// FieldLastPlayedDate holds the string denoting the last_played_date field in the database.
	FieldLastPlayedDate = "last_played_date"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// Table holds the table name of the playstate in the database.
	Table = "play_states"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "play_states"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_playstates"
	// ItemTable is the table that holds the item relation/edge.
	ItemTable = "play_states"
	// ItemInverseTable is the table name for the MediaItem entity.
	// It exists in this package in order to avoid circular dependency with the "mediaitem" package.
	ItemInverseTable = "media_items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "media_item_playstates"
)

// Columns holds all SQL columns for playstate fields.
var Columns = []string{
	FieldID,
	FieldPlayed,
	FieldPlaybackPositionTicks,
	FieldPlayCount,
	FieldLastPlayedDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "play_states"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"media_item_playstates",
	"user_playstates",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlayed holds the default value on creation for the "played" field.
	DefaultPlayed bool
	// DefaultPlaybackPositionTicks holds the default value on creation for the "playback_position_ticks" field.
	DefaultPlaybackPositionTicks int64
	// DefaultPlayCount holds the default value on creation for the "play_count" field.
	DefaultPlayCount int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PlayState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlayed orders the results by the played field.
func ByPlayed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayed, opts...).ToFunc()
}

// ByPlaybackPositionTicks orders the results by the playback_position_ticks field.
func ByPlaybackPositionTicks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaybackPositionTicks, opts...).ToFunc()
}

// ByPlayCount orders the results by the play_count field.
func ByPlayCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayCount, opts...).ToFunc()
}

// ByLastPlayedDate orders the results by the last_played_date field.
func ByLastPlayedDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPlayedDate, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByItemField orders the results by item field.
func ByItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
	)
}
