// Code generated by ent, DO NOT EDIT.

package playstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gartnera/gofin/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PlayState {
	return predicate.PlayState(sql.FieldLTE(FieldID, id))
}

// Played applies equality check predicate on the "played" field. It's identical to PlayedEQ.
func Played(v bool) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldPlayed, v))
}

// PlaybackPositionTicks applies equality check predicate on the "playback_position_ticks" field. It's identical to PlaybackPositionTicksEQ.
func PlaybackPositionTicks(v int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldPlaybackPositionTicks, v))
}

// PlayCount applies equality check predicate on the "play_count" field. It's identical to PlayCountEQ.
func PlayCount(v int) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldPlayCount, v))
}

// LastPlayedDate applies equality check predicate on the "last_played_date" field. It's identical to LastPlayedDateEQ.
func LastPlayedDate(v time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldLastPlayedDate, v))
}

// PlayedEQ applies the EQ predicate on the "played" field.
func PlayedEQ(v bool) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldPlayed, v))
}

// PlayedNEQ applies the NEQ predicate on the "played" field.
func PlayedNEQ(v bool) predicate.PlayState {
	return predicate.PlayState(sql.FieldNEQ(FieldPlayed, v))
}

// PlaybackPositionTicksEQ applies the EQ predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksEQ(v int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldPlaybackPositionTicks, v))
}

// PlaybackPositionTicksNEQ applies the NEQ predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksNEQ(v int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldNEQ(FieldPlaybackPositionTicks, v))
}

// PlaybackPositionTicksIn applies the In predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksIn(vs ...int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldIn(FieldPlaybackPositionTicks, vs...))
}

// PlaybackPositionTicksNotIn applies the NotIn predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksNotIn(vs ...int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldNotIn(FieldPlaybackPositionTicks, vs...))
}

// PlaybackPositionTicksGT applies the GT predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksGT(v int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldGT(FieldPlaybackPositionTicks, v))
}

// PlaybackPositionTicksGTE applies the GTE predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksGTE(v int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldGTE(FieldPlaybackPositionTicks, v))
}

// PlaybackPositionTicksLT applies the LT predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksLT(v int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldLT(FieldPlaybackPositionTicks, v))
}

// PlaybackPositionTicksLTE applies the LTE predicate on the "playback_position_ticks" field.
func PlaybackPositionTicksLTE(v int64) predicate.PlayState {
	return predicate.PlayState(sql.FieldLTE(FieldPlaybackPositionTicks, v))
}

// PlayCountEQ applies the EQ predicate on the "play_count" field.
func PlayCountEQ(v int) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldPlayCount, v))
}

// PlayCountNEQ applies the NEQ predicate on the "play_count" field.
func PlayCountNEQ(v int) predicate.PlayState {
	return predicate.PlayState(sql.FieldNEQ(FieldPlayCount, v))
}

// PlayCountIn applies the In predicate on the "play_count" field.
func PlayCountIn(vs ...int) predicate.PlayState {
	return predicate.PlayState(sql.FieldIn(FieldPlayCount, vs...))
}

// PlayCountNotIn applies the NotIn predicate on the "play_count" field.
func PlayCountNotIn(vs ...int) predicate.PlayState {
	return predicate.PlayState(sql.FieldNotIn(FieldPlayCount, vs...))
}

// PlayCountGT applies the GT predicate on the "play_count" field.
func PlayCountGT(v int) predicate.PlayState {
	return predicate.PlayState(sql.FieldGT(FieldPlayCount, v))
}

// PlayCountGTE applies the GTE predicate on the "play_count" field.
func PlayCountGTE(v int) predicate.PlayState {
	return predicate.PlayState(sql.FieldGTE(FieldPlayCount, v))
}

// PlayCountLT applies the LT predicate on the "play_count" field.
func PlayCountLT(v int) predicate.PlayState {
	return predicate.PlayState(sql.FieldLT(FieldPlayCount, v))
}

// PlayCountLTE applies the LTE predicate on the "play_count" field.
func PlayCountLTE(v int) predicate.PlayState {
	return predicate.PlayState(sql.FieldLTE(FieldPlayCount, v))
}

// LastPlayedDateEQ applies the EQ predicate on the "last_played_date" field.
func LastPlayedDateEQ(v time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldEQ(FieldLastPlayedDate, v))
}

// LastPlayedDateNEQ applies the NEQ predicate on the "last_played_date" field.
func LastPlayedDateNEQ(v time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldNEQ(FieldLastPlayedDate, v))
}

// LastPlayedDateIn applies the In predicate on the "last_played_date" field.
func LastPlayedDateIn(vs ...time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldIn(FieldLastPlayedDate, vs...))
}

// LastPlayedDateNotIn applies the NotIn predicate on the "last_played_date" field.
func LastPlayedDateNotIn(vs ...time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldNotIn(FieldLastPlayedDate, vs...))
}

// LastPlayedDateGT applies the GT predicate on the "last_played_date" field.
func LastPlayedDateGT(v time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldGT(FieldLastPlayedDate, v))
}

// LastPlayedDateGTE applies the GTE predicate on the "last_played_date" field.
func LastPlayedDateGTE(v time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldGTE(FieldLastPlayedDate, v))
}

// LastPlayedDateLT applies the LT predicate on the "last_played_date" field.
func LastPlayedDateLT(v time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldLT(FieldLastPlayedDate, v))
}

// LastPlayedDateLTE applies the LTE predicate on the "last_played_date" field.
func LastPlayedDateLTE(v time.Time) predicate.PlayState {
	return predicate.PlayState(sql.FieldLTE(FieldLastPlayedDate, v))
}

// LastPlayedDateIsNil applies the IsNil predicate on the "last_played_date" field.
func LastPlayedDateIsNil() predicate.PlayState {
	return predicate.PlayState(sql.FieldIsNull(FieldLastPlayedDate))
}

// LastPlayedDateNotNil applies the NotNil predicate on the "last_played_date" field.
func LastPlayedDateNotNil() predicate.PlayState {
	return predicate.PlayState(sql.FieldNotNull(FieldLastPlayedDate))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PlayState {
	return predicate.PlayState(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PlayState {
	return predicate.PlayState(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.PlayState {
	return predicate.PlayState(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.MediaItem) predicate.PlayState {
	return predicate.PlayState(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayState) predicate.PlayState {
	return predicate.PlayState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayState) predicate.PlayState {
	return predicate.PlayState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayState) predicate.PlayState {
	return predicate.PlayState(sql.NotPredicates(p))
}
