// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessToken is the predicate function for accesstoken builders.
type AccessToken func(*sql.Selector)

// Library is the predicate function for library builders.
type Library func(*sql.Selector)

// MediaItem is the predicate function for mediaitem builders.
type MediaItem func(*sql.Selector)

// MetadataCache is the predicate function for metadatacache builders.
type MetadataCache func(*sql.Selector)

// PlayState is the predicate function for playstate builders.
type PlayState func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
